import type {Attribution,Case,CaseListItem,CaseTransaction,CaseSummarySnapshot,GraphLayout,InvestigationOperationalState,Pattern,PatternSummary,RiskAlert,RiskAssessment,RiskDelta,RiskFactor,Trace,Capability,Watch,TimelineEvent,ChangeSet,RealtimeAlert,ChainCapability,CrossChainSummary,CrossChainLink,CrossChainTrace,SystemStatus,DashboardSummary,EntityRecord,EvidenceRecord,ProviderOperationalStatus,AddressAttribution,AttributionSource,IntelligenceSource,AddressScreening,EvidenceLedgerEntry,EvidenceManifest,InvestigationReport,CaseLink,WalletIntelligence,WorkflowEvent,PrimaryPath} from './types';

// Empty string = use Vite dev proxy (relative URLs, no CORS issues regardless of port).
// Undefined/absent = fall back to direct localhost:8000 (for environments without the env file).
// Production: set VITE_API_BASE_URL to the full backend URL (e.g. https://xxx.railway.app).
const _apiBaseRaw = import.meta.env.VITE_API_BASE_URL as string | undefined;
export const API_BASE = _apiBaseRaw === undefined ? 'http://localhost:8000' : _apiBaseRaw.trim();
export type ApiErrorCategory='API_OFFLINE'|'DATABASE_UNAVAILABLE'|'HTTP_ERROR'|'INVALID_RESPONSE';
export class ApiError extends Error{category:ApiErrorCategory;status?:number;requestId?:string;constructor(message:string,category:ApiErrorCategory,status?:number,requestId?:string){super(message);this.name='ApiError';this.category=category;this.status=status;this.requestId=requestId}}
export const apiUrl=(path:string)=>`${API_BASE.replace(/\/$/,'')}${path}`;
async function request<T>(path:string,init?:RequestInit):Promise<T>{
  const controller=new AbortController();
  const timeout=window.setTimeout(()=>controller.abort(),15000);
  try{
    const response=await fetch(apiUrl(path),{...init,signal:init?.signal||controller.signal});
    const requestId=response.headers.get('x-request-id')||undefined;
    let payload:unknown;
    try{payload=await response.json()}catch{throw new ApiError(`INVALID RESPONSE: FastAPI returned an invalid response for ${path}.`, 'INVALID_RESPONSE', response.status, requestId)}
    if(!response.ok){
      const body=payload as any;
      const rawMessage=typeof body?.error?.message==='string'?body.error.message:typeof body?.detail==='string'?body.detail:`Request failed with HTTP ${response.status}`;
      const category=response.status===503?'DATABASE_UNAVAILABLE':'HTTP_ERROR';
      throw new ApiError(`${category==='DATABASE_UNAVAILABLE'?'DATABASE UNAVAILABLE':'HTTP ERROR'}: ${rawMessage}`,category,response.status,requestId)
    }
    return payload as T;
  }catch(error){
    if(error instanceof ApiError)throw error;
    const message=error instanceof DOMException&&error.name==='AbortError'?`API OFFLINE: Request timed out while contacting FastAPI at ${API_BASE}.`:`API OFFLINE: FastAPI unavailable at ${API_BASE}. Start the API and verify port 8000.`;
    throw new ApiError(message,'API_OFFLINE');
  }finally{window.clearTimeout(timeout)}
}
const json=(body:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});

export const api={
 createCase:(body:{title:string;fraud_type:string;priority:string})=>request<Case>('/api/v1/cases',json(body)),
 addWallet:(id:string,address:string)=>request<Case>(`/api/v1/cases/${id}/wallets`,json({address,chain:'ethereum'})),
 trace:(id:string,address:string)=>request<Trace>(`/api/v1/cases/${id}/traces`,json({address,chain:'ethereum',direction:'forward',max_hops:3,max_nodes:100,max_edges:500,max_transactions:500})),
 getCase:(id:string)=>request<Case>(`/api/v1/cases/${encodeURIComponent(id)}`), graph:(id:string)=>request<Trace>(`/api/v1/cases/${encodeURIComponent(id)}/graph`), primaryPath:(id:string)=>request<PrimaryPath>(`/api/v1/cases/${encodeURIComponent(id)}/primary-path`), summary:(id:string)=>request<CaseSummarySnapshot>(`/api/v1/cases/${encodeURIComponent(id)}/summary`),
 operationalState:(id:string)=>request<InvestigationOperationalState>(`/api/v1/cases/${id}/operational-state`),
 investigate:(id:string,body:{address?:string;chain?:string;max_hops?:number;max_nodes?:number;max_edges?:number;max_transactions?:number;start_watch?:boolean;create_report?:boolean})=>request<InvestigationOperationalState>(`/api/v1/cases/${id}/investigate`,json({chain:'ethereum',max_hops:3,max_nodes:100,max_edges:500,max_transactions:500,start_watch:true,create_report:false,...body})),
 graphLayout:(id:string)=>request<GraphLayout>(`/api/v1/cases/${id}/graph/layout`), saveGraphLayout:(id:string,body:Pick<GraphLayout,'node_positions'|'viewport'>)=>request<GraphLayout>(`/api/v1/cases/${id}/graph/layout`,json(body)),
 transactions:(id:string,limit=500)=>request<CaseTransaction[]>(`/api/v1/cases/${id}/transactions?limit=${limit}`),
 attribution:(chain:string,address:string)=>request<Attribution>(`/api/v1/addresses/${chain}/${address}/attribution`),
 analyzePatterns:(caseId:string,traceId:string)=>request<Pattern[]>(`/api/v1/cases/${caseId}/patterns/analyze`,json({trace_id:traceId})),
 patterns:(caseId:string,traceId:string)=>request<Pattern[]>(`/api/v1/cases/${caseId}/patterns?trace_id=${encodeURIComponent(traceId)}`),
 patternSummary:(caseId:string,traceId:string)=>request<PatternSummary>(`/api/v1/cases/${caseId}/patterns/summary?trace_id=${encodeURIComponent(traceId)}`),
 assessRisk:(caseId:string,traceId:string)=>request<RiskAssessment>(`/api/v1/cases/${caseId}/risk/assess`,json({trace_id:traceId})),
 risk:(caseId:string)=>request<RiskAssessment|null>(`/api/v1/cases/${caseId}/risk`), riskHistory:(caseId:string)=>request<RiskAssessment[]>(`/api/v1/cases/${caseId}/risk/history`), riskDelta:(caseId:string)=>request<RiskDelta|null>(`/api/v1/cases/${caseId}/risk/delta`), riskFactors:(caseId:string,assessmentId?:string)=>request<RiskFactor[]>(`/api/v1/cases/${caseId}/risk/factors${assessmentId?`?assessment_id=${encodeURIComponent(assessmentId)}`:''}`), riskAlerts:(caseId:string)=>request<RiskAlert[]>(`/api/v1/cases/${caseId}/risk/alerts`),
 capabilities:()=>request<Capability[]>('/api/v1/provider/capabilities'), realtimeCapabilities:()=>request<Capability[]>('/api/v1/realtime/capabilities'), realtimeHealth:()=>request<Record<string,string>>('/api/v1/realtime/health'),
 watches:(caseId:string)=>request<Watch[]>(`/api/v1/cases/${caseId}/watches`), createWatch:(caseId:string,address:string)=>request<Watch>(`/api/v1/cases/${caseId}/watches`,json({address,chain:'ethereum',expansion_policy:'MANUAL'})), pauseWatch:(caseId:string,id:string)=>request<Watch>(`/api/v1/cases/${caseId}/watches/${id}/pause`,{method:'POST'}), resumeWatch:(caseId:string,id:string)=>request<Watch>(`/api/v1/cases/${caseId}/watches/${id}/resume`,{method:'POST'}), stopWatch:(caseId:string,id:string)=>request<Watch>(`/api/v1/cases/${caseId}/watches/${id}`,{method:'DELETE'}),
 timeline:(caseId:string)=>request<TimelineEvent[]>(`/api/v1/cases/${caseId}/timeline`), changes:(caseId:string)=>request<ChangeSet[]>(`/api/v1/cases/${caseId}/changes`), realtimeAlerts:(caseId:string)=>request<RealtimeAlert[]>(`/api/v1/cases/${caseId}/alerts`), chains:()=>request<ChainCapability[]>('/api/v1/chains'), crossChainSummary:(caseId:string)=>request<CrossChainSummary>(`/api/v1/cases/${caseId}/cross-chain`), crossChainLinks:(caseId:string)=>request<CrossChainLink[]>(`/api/v1/cases/${caseId}/cross-chain/links`), analyzeCrossChain:(caseId:string,rootChain:string,rootAddress:string)=>request<CrossChainTrace>(`/api/v1/cases/${caseId}/cross-chain/analyze`,json({root_chain:rootChain,root_address:rootAddress,chains:['ethereum','tron']}))
};
export const listCases=()=>request<CaseListItem[]>('/api/v1/cases'); export const systemStatus=()=>request<SystemStatus>('/api/v1/system/status'); export const systemDependencies=()=>request<SystemStatus>('/api/v1/system/dependencies'); export const systemProviders=()=>request<ProviderOperationalStatus[]>('/api/v1/system/providers'); export const caseWorkflow=(caseId:string)=>request<WorkflowEvent[]>(`/api/v1/cases/${encodeURIComponent(caseId)}/workflow`); export const dashboardSummary=()=>request<DashboardSummary>('/api/v1/dashboard/summary'); export const walletIntelligence=(chain:string,address:string)=>request<WalletIntelligence>(`/api/v1/wallets/${encodeURIComponent(chain)}/${encodeURIComponent(address)}`); export const listEntities=()=>request<EntityRecord[]>('/api/v1/entities'); export const entityAttributions=(entityId:string)=>request<AddressAttribution[]>(`/api/v1/entities/${encodeURIComponent(entityId)}/attributions`); export const attributionSources=()=>request<AttributionSource[]>('/api/v1/attribution-sources'); export const intelligenceSources=()=>request<IntelligenceSource[]>('/api/v1/intelligence/sources'); export const screenAddress=(chain:string,address:string)=>request<AddressScreening>(`/api/v1/addresses/${encodeURIComponent(chain)}/${encodeURIComponent(address)}/sanctions`); export const listEvidence=(caseId:string)=>request<EvidenceRecord[]>(`/api/v1/cases/${encodeURIComponent(caseId)}/evidence`); export const evidenceLedger=(caseId:string)=>request<EvidenceLedgerEntry[]>(`/api/v1/cases/${encodeURIComponent(caseId)}/evidence/ledger`); export const createEvidenceManifest=(caseId:string,createdBy?:string)=>request<EvidenceManifest>(`/api/v1/cases/${encodeURIComponent(caseId)}/evidence/manifest`,json(createdBy?{created_by:createdBy}:{})); export const listReports=(caseId:string)=>request<InvestigationReport[]>(`/api/v1/cases/${encodeURIComponent(caseId)}/reports`); export const createReport=(caseId:string,reportType='INVESTIGATION_SUMMARY',traceId?:string)=>request<InvestigationReport>(`/api/v1/cases/${encodeURIComponent(caseId)}/reports`,json({report_type:reportType,trace_id:traceId,created_by:'investigator-session'})); export const relatedCases=(caseId:string)=>request<CaseLink[]>(`/api/v1/cases/${encodeURIComponent(caseId)}/related`); export const listAlerts=()=>request<RealtimeAlert[]>('/api/v1/alerts'); export const reviewAlert=(caseId:string,alertId:string,action:'ACKNOWLEDGE'|'DISMISS'|'ESCALATE',note?:string)=>request<RealtimeAlert>(`/api/v1/cases/${encodeURIComponent(caseId)}/alerts/${encodeURIComponent(alertId)}/review`,json({action,note})); export const providerStatuses=()=>request<ProviderOperationalStatus[]>('/api/v1/providers');
export const caseScreenings=(caseId:string)=>request<AddressScreening[]>(`/api/v1/cases/${encodeURIComponent(caseId)}/cyber/screening`); export const screenCase=(caseId:string)=>request<Record<string,unknown>>(`/api/v1/cases/${encodeURIComponent(caseId)}/cyber/screen`,{method:'POST'});
export const databaseDiagnostics=()=>request<Record<string,unknown>>('/api/v1/system/database'); export const databaseIntegrity=()=>request<Record<string,unknown>>('/api/v1/system/database/integrity'); export const sanctionsStatus=()=>request<Record<string,unknown>>('/api/v1/intelligence/sanctions/status');
export const createSimulatedWatch=(caseId:string,address:string)=>request<Watch>(`/api/v1/cases/${encodeURIComponent(caseId)}/watches`,json({address,chain:'ethereum',source:'SIMULATED'})); export const sendSimulatedEvent=(event:Record<string,unknown>)=>request<unknown>('/api/v1/realtime/simulated/events',json(event)); export const generateSyntheticInvestigation=(eventCount=50,scenario='MULTI_STAGE_FRAUD',scenarioSeed='rrr-synthetic-case')=>request<{case_id:string;trace_id:string;watch_id:string;report_id:string;mode:string;flags:{type:string;severity:string;confidence:string;pattern_id:string}[];counts:Record<string,number>;synthetic?:{requested_events:number;processed_events:number;scenario:string};note:string}>('/api/v1/dev/synthetic/cases',json({event_count:eventCount,scenario,scenario_seed:scenarioSeed})); export const startInvestigationDemo=()=>request<{case_id:string;trace_id:string;mode:string}>('/api/v1/dev/demo/start',json({})); export const syntheticStatus=()=>request<any>('/api/v1/dev/realtime/status'); export const syntheticEvents=(limit=50)=>request<any>(`/api/v1/dev/realtime/events?limit=${limit}`); export const syntheticControl=(action:'start'|'pause'|'resume'|'stop'|'step',body:Record<string,unknown>={})=>request<any>(`/api/v1/dev/realtime/${action}`,json(body)); export const syntheticScenario=(scenario:string,body:Record<string,unknown>)=>request<any>(`/api/v1/dev/realtime/scenarios/${encodeURIComponent(scenario)}/start`,json(body));
export const createInvestigation=(body:{title:string;fraud_type:string;priority:string;external_case_reference?:string;description?:string})=>request<Case>('/api/v1/cases',json(body)); export const addInvestigationWallet=(caseId:string,address:string,chain:string)=>request<Case>(`/api/v1/cases/${encodeURIComponent(caseId)}/wallets`,json({address,chain})); export const addInvestigationTransaction=(caseId:string,txHash:string,chain:string)=>request<Case>(`/api/v1/cases/${encodeURIComponent(caseId)}/transactions`,json({tx_hash:txHash,chain})); export const traceInvestigation=(caseId:string,address:string,chain:string)=>request<Trace>(`/api/v1/cases/${encodeURIComponent(caseId)}/traces`,json({address,chain,direction:'forward',max_hops:3,max_nodes:100,max_edges:500,max_transactions:500})); export async function downloadReportPdf(caseId:string,reportId:string){const response=await fetch(apiUrl(`/api/v1/cases/${encodeURIComponent(caseId)}/reports/${encodeURIComponent(reportId)}/pdf`));if(!response.ok)throw new Error(`PDF export failed (${response.status})`);const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`crypto-fraud-report-${caseId.slice(0,8)}-${reportId.slice(0,8)}.pdf`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
