import {useEffect,useState} from 'react';
import {Shell} from './components/Shell';
import {GraphInspector} from './components/GraphInspector';
import {PatternsPage} from './components/PatternsPage';
import {RiskPage} from './components/RiskPage';
import {RealtimePage} from './components/RealtimePage';
import {CrossChainPage} from './components/CrossChainPage';
import {api} from './api';
import type {Case,Trace} from './types';
import {Dashboard,GenericPage,Intake,Workspace} from './pages';

export default function App(){
 const [route,setRoute]=useState(location.hash.slice(1)||'dashboard');
 const [caseData,setCaseData]=useState<Case|null>(null);
 const [trace,setTrace]=useState<Trace|null>(null);
 const [apiState,setApiState]=useState('UNKNOWN');
 useEffect(()=>{const onHash=()=>setRoute(location.hash.slice(1)||'dashboard');addEventListener('hashchange',onHash);api.capabilities().then(()=>setApiState('ONLINE')).catch(()=>setApiState('NOT CONFIGURED'));return()=>removeEventListener('hashchange',onHash)},[]);
 function navigate(next:string){location.hash=next;setRoute(next)}
 function completed(caseResult:Case,traceResult:Trace){setCaseData(caseResult);setTrace(traceResult);navigate('case')}
 let page;
 if(route==='dashboard') page=<Dashboard onNavigate={navigate}/>;
 else if(route==='investigate'||route==='intake') page=<Intake onComplete={completed}/>;
 else if(route==='case'&&caseData&&trace) page=<Workspace caseData={caseData} trace={trace} onNavigate={navigate}/>;
 else if(route==='graph'&&trace) page=<><PageTitle eyebrow="INVESTIGATION / GRAPH" title="Transaction graph"/><GraphInspector trace={trace}/></>;
 else if(route==='patterns'&&caseData&&trace) page=<PatternsPage caseData={caseData} trace={trace} onNavigate={navigate}/>;
 else if(route==='risk'&&caseData&&trace) page=<RiskPage caseData={caseData} trace={trace} onNavigate={navigate}/>;
 else if((route==='monitoring'||route==='realtime')&&caseData&&trace) page=<RealtimePage caseData={caseData} trace={trace}/>;
 else if((route==='cross-chain'||route==='chains')&&caseData&&trace) page=<CrossChainPage caseData={caseData} trace={trace}/>;
 else if(route==='cases') page=<GenericPage eyebrow="INVESTIGATIONS / CASES" title="Case registry" text="Case index APIs are not yet configured in this environment. Open a new investigation to create a persisted case."/>;
 else if(route==='wallets') page=<GenericPage eyebrow="INTELLIGENCE / WALLET" title="Wallet intelligence" text="Search and inspect observed address activity, related cases, attribution and evidence."/>;
 else if(route==='entities') page=<GenericPage eyebrow="INTELLIGENCE / ENTITIES" title="Entities / VASPs" text="Source-backed entity attribution will appear here. No ownership or regulatory conclusion is implied."/>;
 else if(route==='evidence') page=<GenericPage eyebrow="CASEWORK / EVIDENCE" title="Evidence workspace" text="Review blockchain evidence, attribution evidence, case documents and investigator notes."/>;
 else if(route==='alerts') page=<GenericPage eyebrow="OPERATIONS / ALERTS" title="Alert center" text="Alerts will be generated by supported analytical capabilities only. Real-time monitoring is not configured."/>;
 else if(route==='reports') page=<GenericPage eyebrow="CASEWORK / REPORTS" title="Investigation reports" text="Evidence-backed report previews will appear here when report generation is enabled."/>;
 else page=<Dashboard onNavigate={navigate}/>;
 return <Shell route={route} onNavigate={navigate}><div className="api-notice"><span className={apiState==='ONLINE'?'ok-dot':'warn-dot'}/> API {apiState} · Historical blockchain data only</div>{page}</Shell>
}
function PageTitle({eyebrow,title}:{eyebrow:string;title:string}){return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1></div></div>}
