import React from 'react';
import {createRoot} from 'react-dom/client';
import App from './App';
import './styles.css';
import './connected-intake.css';
import './graph.css';
import './graph-readable.css';
import './graph-accessibility.css';
import './app.css';
import './pattern.css';
import './risk.css';
import './risk-overlay.css';
import './realtime.css';
import './cross-chain.css';
import './evidence-readable.css';
import './command-center.css';
import './synthetic-generator.css';
import './synthetic-console.css';
import './live-intelligence.css';
import './run-demo.css';

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
