import {useState} from 'react';
import type {Case,Trace} from '../types';
import {addInvestigationTransaction,addInvestigationWallet,createInvestigation,traceInvestigation,api} from '../api';

const FIXTURE_ROOT='0x1111111111111111111111111111111111111111';
export function ConnectedIntake({onComplete}:{onComplete:(caseData:Case,trace:Trace)=>void}){
 const [title,setTitle]=useState('');const [reference,setReference]=useState('');const [notes,setNotes]=useState('');const [fraudType,setFraudType]=useState('Investment fraud');const [chain,setChain]=useState('ethereum');const [wallet,setWallet]=useState('');const [txHash,setTxHash]=useState('');const [source,setSource]=useState('MANUAL');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(){if(!valid){setError(chain==='ethereum'?'Enter a valid 0x Ethereum address, or use the development fixture wallet.':'The local development provider supports Ethereum only. Choose Ethereum to run this workflow.');return}setBusy(true);setError('');try{const created=await createInvestigation({title:title||'Untitled investigation',fraud_type:fraudType,priority:'HIGH',external_case_reference:reference||undefined,description:`Source: ${source}\n${notes}`.trim()});await addInvestigationWallet(created.case_id,wallet,chain);if(txHash)await addInvestigationTransaction(created.case_id,txHash,chain);const result=await traceInvestigation(created.case_id,wallet,chain);await api.analyzePatterns(created.case_id,result.trace_id);await api.assessRisk(created.case_id,result.trace_id);onComplete(await api.getCase(created.case_id),result)}catch(e){setError(e instanceof Error?e.message:'Investigation workflow failed. Check the API status and provider mode.')}finally{setBusy(false)}}
 const valid=chain==='ethereum'?/^0x[\da-f]{40}$/i.test(wallet):/^T[1-9A-HJ-NP-Za-km-z]{33}$/.test(wallet);
 return <><div className="page-header"><div><div className="eyebrow">INVESTIGATIONS / CONNECTED INTAKE</div><h1>New investigation</h1><p className="muted">Create a persisted case, submit a wallet, then run the configured provider trace.</p></div><span className="capability-pill historical">BACKEND WORKFLOW</span></div><div className="intake-grid"><section className="surface intake-form"><div className="panel-title"><div className="eyebrow">CASE INTAKE</div><h3>Complaint and asset context</h3></div><label>Complaint source<select value={source} onChange={e=>setSource(e.target.value)}><option>MANUAL</option><option>NCRP</option><option>SAHYOG</option><option>OTHER</option></select></label><label>Case title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Project Northstar"/></label><label>Complaint/reference ID<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Optional external reference"/></label><label>Victim notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observed complaint context" rows={4}/></label><label>Fraud type<select value={fraudType} onChange={e=>setFraudType(e.target.value)}><option>Investment fraud</option><option>Romance scam</option><option>Phishing</option><option>Ransomware</option></select></label><label>Blockchain/network<select value={chain} onChange={e=>setChain(e.target.value)}><option value="ethereum">Ethereum · local fixture/live Alchemy</option><option value="tron">Tron · requires TronGrid</option></select></label><label>Reported wallet<input className="mono" value={wallet} onChange={e=>setWallet(e.target.value)} placeholder="0x..."/><button type="button" className="fixture-fill" onClick={()=>{setChain('ethereum');setWallet(FIXTURE_ROOT)}}>USE DEVELOPMENT FIXTURE WALLET</button></label><label>Optional transaction hash<input className="mono" value={txHash} onChange={e=>setTxHash(e.target.value)} placeholder="0x..."/></label>{!valid&&<div className="intake-help">Enter a valid wallet address to enable the workflow, or use the development fixture wallet.</div>}{error&&<div className="error" role="alert">{error}</div>}<button type="button" className="primary wide" disabled={busy} onClick={submit}>{busy?'Running case → wallet → trace → intelligence…':'Create case and trace wallet'} <span>→</span></button></section><aside className="surface intake-side"><div className="callout"><div className="eyebrow">REAL DATA FLOW</div><h3>Case → wallet → provider → graph</h3><p>The form submits case metadata to FastAPI, persists the wallet, invokes the configured chain provider and continues into patterns and risk.</p><div className="capability-pill simulated">NCRP / SAHYOG ADAPTERS · SIMULATED</div></div></aside></div></>
}
