import {useEffect,useState} from 'react';
import {api} from '../api';
import type {Case,Trace,ChainCapability,CrossChainSummary,CrossChainLink,CrossChainTrace} from '../types';

export function CrossChainPage({caseData,trace}:{caseData:Case;trace:Trace}){
 const [chains,setChains]=useState<ChainCapability[]>([]); const [summary,setSummary]=useState<CrossChainSummary|null>(null); const [links,setLinks]=useState<CrossChainLink[]>([]); const [analysis,setAnalysis]=useState<CrossChainTrace|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const refresh=()=>Promise.all([api.chains(),api.crossChainSummary(caseData.case_id),api.crossChainLinks(caseData.case_id)]).then(([c,s,l])=>{setChains(c);setSummary(s);setLinks(l)}).catch(e=>setError(e.message)); useEffect(()=>{refresh()},[caseData.case_id]);
 async function analyze(){setBusy(true);setError('');try{setAnalysis(await api.analyzeCrossChain(caseData.case_id,trace.root_address.startsWith('T')?'tron':'ethereum',trace.root_address));await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><div className="page-header"><div><div className="eyebrow">RRR / CROSS-CHAIN FORENSICS</div><h1>Supported network intelligence</h1><p className="muted">Observed transfers and confidence-scored bridge relationships remain separate facts.</p></div><button className="primary-button" disabled={busy} onClick={analyze}>{busy?'Analyzing...':'Analyze persisted observations'}</button></div>
 <div className="chain-lanes">{chains.map(c=><div className="chain-lane" key={c.chain_id}><div className="lane-head"><span className="chain-mark">{c.chain_id==='ethereum'?'E':'T'}</span><div><strong>{c.name}</strong><small>{c.family} | {c.native_asset} | {c.provider}</small></div><span className={'status-pill '+(c.historical_capability==='SUPPORTED'?'good':'warn')}>{c.historical_capability}</span></div><div className="lane-meta"><span>Historical <b>{c.historical_capability}</b></span><span>Realtime <b>{c.realtime_capability}</b></span><span>Tokens <b>{c.token_transfer_capability}</b></span></div></div>)}</div>
 <div className="cross-summary">{[['CHAINS INVOLVED',summary?.chains.length||0],['CROSS-CHAIN MOVEMENTS',summary?.cross_chain_movements||0],['STRONG / EXACT LINKS',summary?.strong_or_exact_links||0],['UNRESOLVED LINKS',summary?.unresolved_links||0]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div>
 {error&&<div className="error-text cross-error">{error}</div>}
 <section className="panel cross-flow"><div className="panel-head"><div><span className="eyebrow">CROSS-CHAIN FLOW</span><h2>Observed - inferred</h2></div>{analysis&&<span className="status-pill">{analysis.status} | {analysis.cross_chain_hops} CROSS-CHAIN HOP(S)</span>}</div>{!links.length?<div className="empty-state">No persisted cross-chain links. Add normalized observations through an authorized provider or the explicitly simulated intake boundary before analyzing.</div>:links.map(link=><div className="link-row" key={link.link_id}><div className="link-chain source-chain"><b>{link.source.chain.toUpperCase()}</b><span>{link.source.address.slice(0,10)}...{link.source.address.slice(-6)}</span><small>{link.source_transaction_hash.slice(0,14)}...</small></div><div className="link-arrow"><span>|</span><b>{link.correlation_level}</b><small>{(link.confidence_score*100).toFixed(0)}% confidence</small></div><div className="link-chain destination-chain"><b>{link.destination?.chain?.toUpperCase()||'DESTINATION UNRESOLVED'}</b><span>{link.destination?`${link.destination.address.slice(0,10)}...${link.destination.address.slice(-6)}`:'No destination asserted'}</span><small>{link.destination_transaction_hash?link.destination_transaction_hash.slice(0,14)+'...':'No destination transaction'}</small></div><div className="link-reason"><span className="status-pill">{link.observed_or_inferred}</span><p>{link.explanation}</p><small>{link.correlation_reasons.join(' | ')||'CROSS-CHAIN LINK: UNKNOWN'}</small></div></div>)}</section>
 {analysis&&<section className="panel cross-reasoning"><div className="eyebrow">CROSS-CHAIN REASONING</div><h2>{analysis.primary_path?.status==='ATTRIBUTED'?'Source chain / Bridge / Destination chain / VASP':'CROSS-CHAIN LINK: UNKNOWN'}</h2>{analysis.primary_path?.status==='ATTRIBUTED'?<><div className="cross-primary-chain">{analysis.primary_path.chain_labels.join(' -> ')}{' -> '}{analysis.primary_path.terminal_entity_name}</div><div className="cross-reason-grid"><span>Bridge / protocol<b>{analysis.cross_chain_transfers?.map(item=>item.bridge_protocol).join(', ')||'Unavailable'}</b></span><span>Asset<b>{analysis.cross_chain_transfers?.map(item=>item.asset).join(', ')||'Unavailable'}</b></span><span>Amount<b>{analysis.cross_chain_transfers?.map(item=>item.amount).join(', ')||'Unavailable'}</b></span><span>Hop count<b>{analysis.primary_path.hops}</b></span><span>Confidence<b>{analysis.primary_path.attribution}</b></span><span>Evidence<b>{analysis.primary_path.evidence_ids.join(', ')||'None linked'}</b></span></div><p>{analysis.primary_path.why}</p></>:<p>No verified cross-chain correlation was established. No destination-chain transaction or VASP endpoint is asserted.</p>}</section>}
 </>
}
