import {useEffect,useState} from 'react';
import type {EvidenceLedgerEntry,EvidenceManifest} from '../types';
import {createEvidenceManifest,evidenceLedger} from '../api';

export function EvidenceLedgerPanel({caseId}:{caseId:string}){
  const [entries,setEntries]=useState<EvidenceLedgerEntry[]>([]); const [manifest,setManifest]=useState<EvidenceManifest|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{evidenceLedger(caseId).then(setEntries).catch(e=>setError(e instanceof Error?e.message:'Evidence ledger unavailable'))},[caseId]);
  async function manifestEvidence(){setBusy(true);setError('');try{const created=await createEvidenceManifest(caseId,'investigator-session');setManifest(created);setEntries(await evidenceLedger(caseId))}catch(e){setError(e instanceof Error?e.message:'Unable to create integrity manifest')}finally{setBusy(false)}}
  return <div className="surface evidence-ledger-panel"><div className="panel-title"><div className="eyebrow">CHAIN OF CUSTODY</div><h3>Canonical evidence ledger</h3></div><p className="muted">Evidence observations are hash-linked for integrity review. This is not an export or legal certification.</p>{error&&<div className="error" role="alert">{error}</div>}<div className="ledger-toolbar"><span className="capability-pill historical">{entries.length} ledger entries</span><button className="secondary" disabled={busy||!entries.length} onClick={manifestEvidence}>{busy?'Hashing…':'Create integrity manifest'}</button></div>{manifest&&<div className="ledger-manifest" role="status"><b>Manifest created</b><span className="mono">{manifest.content_hash}</span><small>{manifest.evidence_count} evidence records · {manifest.algorithm}</small></div>}{entries.length?<div className="case-table">{entries.map(({evidence,chain_of_custody,manifest_ids})=><div className="case-row" key={evidence.evidence_id}><strong>{evidence.evidence_id}</strong><span>{evidence.integrity_status||'UNVERIFIED'}</span><span>{manifest_ids.length} manifest{manifest_ids.length===1?'':'s'}</span><span>{chain_of_custody.length} custody event{chain_of_custody.length===1?'':'s'}</span><small className="mono">{evidence.content_hash||'Hash not captured'}</small></div>)}</div>:<div className="empty-block"><b>No ledger entries available</b><p>Run a trace or ingest an observation before creating an integrity manifest.</p></div>}</div>
}
