import {useEffect,useMemo,useState} from 'react';
import type {Edge,Node,RiskAssessment,Trace} from '../types';
import {api} from '../api';

const short=(value:string)=>value.length>18?`${value.slice(0,8)}…${value.slice(-6)}`:value;
const nodeKey=(node:Node)=>node.id||node.address;
const chainKey=(chain:string|undefined)=>chain||'ethereum';
const identity=(chain:string|undefined,address:string)=>`${chainKey(chain)}:${chainKey(chain)==='ethereum'?address.toLowerCase():address}`;
type Point={x:number;y:number};

function layout(nodes:Node[],edges:Edge[],root:string){
  const rootKey=identity(nodes.find(node=>node.address.toLowerCase()===root.toLowerCase())?.chain,root);
  const adjacency=new Map<string,string[]>();
  for(const edge of edges){
    const source=identity(edge.transfer.chain,edge.source); const target=identity(edge.transfer.chain,edge.target);
    adjacency.set(source,[...(adjacency.get(source)||[]),target]);
  }
  const depth=new Map<string,number>([[rootKey,0]]); const queue=[rootKey];
  while(queue.length){const current=queue.shift()!;for(const next of adjacency.get(current)||[]){if(!depth.has(next)){depth.set(next,(depth.get(current)||0)+1);queue.push(next)}}}
  const groups=new Map<number,Node[]>();
  for(const node of nodes){const level=depth.get(identity(node.chain,node.address))??0;const group=groups.get(level)||[];group.push(node);groups.set(level,group)}
  const positions=new Map<string,Point>(); const maxLevel=Math.max(...Array.from(groups.keys()),0); const height=Math.max(560,Math.max(...Array.from(groups.values()).map(group=>group.length),1)*112);
  for(const [level,group] of groups){const x=120+(level/Math.max(maxLevel,1))*760;group.forEach((node,index)=>positions.set(identity(node.chain,node.address),{x,y:72+(index+1)*(height-120)/(group.length+1)}))}
  return positions;
}

export function GraphInspector({trace}:{trace:Trace}){
  const [node,setNode]=useState<Node|null>(null); const [edge,setEdge]=useState<Edge|null>(null); const [scale,setScale]=useState(1); const [asset,setAsset]=useState('ALL'); const [risk,setRisk]=useState<RiskAssessment|null>(null);
  useEffect(()=>{api.risk(trace.case_id).then(setRisk).catch(()=>setRisk(null))},[trace.case_id,trace.trace_id]);
  const assets=useMemo(()=>Array.from(new Set(trace.edges.map(item=>item.transfer.asset).filter(Boolean))).sort(),[trace.edges]);
  const visibleEdges=useMemo(()=>asset==='ALL'?trace.edges:trace.edges.filter(item=>item.transfer.asset===asset),[asset,trace.edges]);
  const visibleAddresses=new Set(visibleEdges.flatMap(item=>[identity(item.transfer.chain,item.source),identity(item.transfer.chain,item.target)]));
  const visibleNodes=trace.nodes.filter(item=>visibleAddresses.has(identity(item.chain,item.address))||item.address.toLowerCase()===trace.root_address.toLowerCase());
  const positions=useMemo(()=>layout(visibleNodes,visibleEdges,trace.root_address),[visibleNodes,visibleEdges,trace.root_address]);
  const riskTransactions=new Set(risk?.factors.flatMap(item=>item.transaction_hashes)||[]);
  const edgeFactors=(item:Edge)=>risk?.factors.filter(factor=>factor.transaction_hashes.includes(item.transaction_hash))||[];
  const nodeFactors=(item:Node)=>risk?.factors.filter(factor=>factor.transaction_hashes.some(tx=>trace.edges.some(itemEdge=>itemEdge.transaction_hash===tx&&(itemEdge.source===item.address||itemEdge.target===item.address))))||[];
  const point=(address:string,chain?:string)=>positions.get(identity(chain,address))||{x:0,y:0}; const selectedNodeAddress=node?identity(node.chain,node.address):undefined;
  return <div className="graph-workspace">
    <div className="graph-commandbar"><div className="graph-command-title"><span className="eyebrow">TRANSACTION GRAPH / OBSERVED FLOW</span><strong>{trace.direction==='backward'?'Inbound funding trace':'Outbound fund-flow trace'}</strong><span className="graph-source">{trace.provider} · {trace.mode} · {trace.status}</span></div><div className="graph-command-actions"><span className={`data-badge ${trace.status==='PARTIAL'?'warning':''}`}>{trace.status==='PARTIAL'?'PARTIAL TRACE':'OBSERVED DATA'}</span><button className="icon-action" aria-label="Zoom out" onClick={()=>setScale(Math.max(.7,scale-.1))}>−</button><button className="fit-action" onClick={()=>setScale(1)}>FIT</button><button className="icon-action" aria-label="Zoom in" onClick={()=>setScale(Math.min(1.35,scale+.1))}>+</button></div></div>
    <div className="graph-filterbar"><label>ASSET<select value={asset} onChange={event=>setAsset(event.target.value)}><option value="ALL">ALL ASSETS</option>{assets.map(item=><option key={item} value={item}>{item}</option>)}</select></label><span className="filter-readout">{visibleNodes.length} nodes · {visibleEdges.length} edges · {trace.metrics.unique_transaction_count} transactions</span><span className="filter-readout">MAX HOP <b>{trace.metrics.maximum_hop}</b></span><button className="secondary" onClick={()=>{setAsset('ALL');setScale(1);setNode(null);setEdge(null)}}>RESET VIEW</button></div>
    <div className="graph-main-grid"><section className="graph-surface" aria-label="Observed blockchain transaction graph"><div className="graph-surface-header"><div><b>OBSERVED BLOCKCHAIN FLOW</b><small>Edges retain transaction and evidence references. Select an observation to inspect it.</small></div><span className="graph-legend-inline"><i className="legend-root"/>ROOT <i className="legend-wallet"/>WALLET <i className="legend-risk"/>RISK-LINKED</span></div>
      {visibleEdges.length===0?<div className="graph-empty"><span>⌁</span><b>No graph observations match this filter</b><p>Change the asset filter or run a bounded trace with persisted blockchain observations.</p></div>:<div className="graph-viewport"><svg viewBox="0 0 1000 500" role="img" aria-label="Directed graph of observed blockchain transfers" style={{transform:`scale(${scale})`}}><defs><marker id="graph-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7 Z" fill="currentColor"/></marker></defs><g className="graph-grid-lines">{Array.from({length:6},(_,index)=><line key={`h-${index}`} x1="0" y1={index*100} x2="1000" y2={index*100}/>)}{Array.from({length:11},(_,index)=><line key={`v-${index}`} x1={index*100} y1="0" x2={index*100} y2="500"/>)}</g>
        {visibleEdges.map(item=>{const source=point(item.source,item.transfer.chain);const target=point(item.target,item.transfer.chain);const bearing=riskTransactions.has(item.transaction_hash);const selected=edge?.edge_id===item.edge_id;const token=item.transfer.transfer_type!=='native';return <g key={item.edge_id} className={`graph-edge ${bearing?'risk-bearing':''} ${token?'token-edge':''} ${selected?'selected':''}`} role="button" tabIndex={0} aria-label={`Inspect transfer ${short(item.transaction_hash)} from ${short(item.source)} to ${short(item.target)}`} onClick={()=>{setEdge(item);setNode(null)}} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setEdge(item);setNode(null)}}}><line x1={source.x} y1={source.y} x2={target.x} y2={target.y} markerEnd="url(#graph-arrow)"/><rect x={(source.x+target.x)/2-52} y={(source.y+target.y)/2-15} width="104" height="28" rx="4"/><text x={(source.x+target.x)/2} y={(source.y+target.y)/2-1} textAnchor="middle">{short(item.transfer.amount)} {item.transfer.asset}</text><text className="edge-hop" x={(source.x+target.x)/2} y={(source.y+target.y)/2+10} textAnchor="middle">HOP {item.hop}</text></g>})}
        {visibleNodes.map(item=>{const position=point(item.address,item.chain);const isRoot=item.address.toLowerCase()===trace.root_address.toLowerCase();const isContract=item.node_type==='CONTRACT';const nodeRisk=nodeFactors(item).length>0;const selected=selectedNodeAddress===identity(item.chain,item.address);return <g key={nodeKey(item)} className={`graph-node ${isRoot?'root':''} ${isContract?'contract':''} ${nodeRisk?'risk-node':''} ${selected?'selected':''}`} role="button" tabIndex={0} aria-label={`Inspect ${item.node_type} ${short(item.address)}`} transform={`translate(${position.x} ${position.y})`} onClick={()=>{setNode(item);setEdge(null)}} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setNode(item);setEdge(null)}}}><circle r={isRoot?34:29}/><circle className="node-core" r={isRoot?26:21}/><text className="node-type" textAnchor="middle" y="4">{isRoot?'ROOT':isContract?'CONTRACT':'WALLET'}</text><text className="node-label" textAnchor="middle" y="52">{short(item.address)}</text><text className="node-meta" textAnchor="middle" y="67">{item.transaction_count} OBSERVED</text></g>})}</svg></div>}
      <div className="graph-surface-footer"><span><i className="legend-root"/>Reported wallet</span><span><i className="legend-wallet"/>Observed address</span><span><i className="legend-contract"/>Contract interaction</span><span><i className="legend-risk"/>Risk-linked evidence</span><span className="footer-note">Visual relationship is derived from persisted observations.</span></div></section><aside className="graph-inspector-panel" aria-live="polite">{node?<NodeDetails node={node} factors={nodeFactors(node)}/>:edge?<EdgeDetails edge={edge} factors={edgeFactors(edge)}/>:<EmptyInspector trace={trace} risk={risk}/>}</aside></div>
    <div className="graph-metrics"><Metric label="NODES" value={trace.metrics.node_count}/><Metric label="EDGES" value={trace.metrics.edge_count}/><Metric label="TRANSACTIONS" value={trace.metrics.unique_transaction_count}/><Metric label="ASSETS" value={trace.metrics.unique_asset_count}/><Metric label="PATHS" value={trace.metrics.path_count}/><Metric label="MAX HOP" value={trace.metrics.maximum_hop}/></div><GraphAnalysisRail trace={trace} edges={visibleEdges}/>
  </div>
}

export function GraphUnavailable({onNavigate}:{onNavigate:(route:string)=>void}){return <section className="graph-unavailable" aria-labelledby="graph-unavailable-title"><div className="eyebrow">INVESTIGATION / GRAPH</div><h1 id="graph-unavailable-title">Transaction graph</h1><div className="graph-unavailable-card"><div className="empty-orbit" aria-hidden="true">+</div><div><span className="data-badge warning">NO ACTIVE TRACE</span><h2>Load an evidence-backed trace to inspect the graph</h2><p>The graph workspace renders persisted blockchain observations only. Start a bounded investigation to see nodes, transaction edges, hop distance, and evidence references here.</p><div className="graph-unavailable-actions"><button className="primary" onClick={()=>onNavigate('investigate')}>START INVESTIGATION</button><button className="secondary" onClick={()=>onNavigate('cases')}>VIEW CASES</button></div></div></div></section>}

function GraphAnalysisRail({trace,edges}:{trace:Trace;edges:Edge[]}){const recent=[...edges].filter(item=>item.transfer.timestamp).sort((a,b)=>String(b.transfer.timestamp).localeCompare(String(a.transfer.timestamp))).slice(0,4);return <section className="graph-analysis-rail" aria-label="Observed flow analysis"><div className="analysis-heading"><div><div className="eyebrow">FLOW ANALYSIS / OBSERVED FACTS</div><h2>Investigation trace readout</h2></div><span className="data-badge">EVIDENCE-BACKED</span></div><div className="analysis-grid"><div className="analysis-card"><span className="analysis-label">PATHS RECONSTRUCTED</span><b>{trace.metrics.path_count}</b><small>Persisted paths available for inspection</small></div><div className="analysis-card"><span className="analysis-label">OBSERVATION WINDOW</span><b>{recent.length?`${recent.length} recent`: 'Unavailable'}</b><small>Latest timestamped transfers in the selected view</small></div><div className="analysis-card analysis-activity"><span className="analysis-label">LATEST OBSERVED ACTIVITY</span>{recent.length?recent.map(item=><div className="activity-row" key={item.edge_id}><span className="mono">{short(item.transaction_hash)}</span><span>{item.transfer.asset} {item.transfer.amount}</span><time>{new Date(item.transfer.timestamp!).toLocaleString()}</time></div>):<small>No timestamped observations available in this trace.</small>}</div></div>{trace.limitations.length>0&&<div className="analysis-limitations"><b>TRACE LIMITATIONS</b><span>{trace.limitations.join(' / ')}</span></div>}</section>}

function NodeDetails({node,factors}:{node:Node;factors:RiskAssessment['factors']}){return <><InspectorHeading eyebrow="NODE OBSERVATION" title={short(node.address)} badge={node.node_type}/><div className="address-block mono">{node.address}</div><dl className="inspector-list"><dt>CHAIN</dt><dd>{node.chain||'Ethereum (legacy trace)'}</dd><dt>ACTIVITY COUNT</dt><dd>{node.transaction_count} observed transactions</dd><dt>FIRST SEEN</dt><dd>{node.first_seen||'Unavailable from persisted observation'}</dd><dt>LAST SEEN</dt><dd>{node.last_seen||'Unavailable from persisted observation'}</dd><dt>RISK-LINKED FACTORS</dt><dd>{factors.length?factors.map(item=><span className="factor-chip" key={item.factor_id}>{item.name} +{item.contribution}</span>):'No linked risk factor in current assessment'}</dd></dl><div className="inspector-note">Node identity is an observed chain/address record. Entity ownership is not inferred by this graph.</div></>}
function EdgeDetails({edge,factors}:{edge:Edge;factors:RiskAssessment['factors']}){return <><InspectorHeading eyebrow="OBSERVED TRANSFER" title={`${edge.transfer.amount} ${edge.transfer.asset}`} badge="EVIDENCE"/><div className="evidence-state"><span className="status-mark">✓</span><div><b>Verified on-chain observation</b><small>{edge.transfer.transfer_type} · HOP {edge.hop}</small></div></div>{factors.length>0&&<div className="risk-callout"><span>RISK-LINKED</span><b>{factors.map(item=>`${item.name} +${item.contribution}`).join(' · ')}</b><small>Derived assessment reference; underlying graph fact is unchanged.</small></div>}<dl className="inspector-list"><dt>TRANSACTION HASH</dt><dd className="hash-value">{edge.transaction_hash}</dd><dt>FROM</dt><dd className="hash-value">{edge.source}</dd><dt>TO</dt><dd className="hash-value">{edge.target}</dd><dt>BLOCK</dt><dd>{edge.transfer.block_number??'Unavailable'}</dd><dt>TIME</dt><dd>{edge.transfer.timestamp?new Date(edge.transfer.timestamp).toLocaleString():'Unavailable'}</dd><dt>PROVIDER</dt><dd>{edge.transfer.provider}</dd><dt>EVIDENCE</dt><dd className="verified-text">{edge.evidence_id||'Evidence reference unavailable'}</dd></dl><button className="secondary wide-action" onClick={()=>navigator.clipboard?.writeText(edge.transaction_hash)}>COPY TRANSACTION HASH</button></>}
function EmptyInspector({trace,risk}:{trace:Trace;risk:RiskAssessment|null}){return <div className="inspector-empty"><span>⌁</span><div className="eyebrow">INSPECTOR READY</div><h3>Select a node or edge</h3><p>Review the exact address, transaction, asset, block, provider, and evidence reference behind each observed relationship.</p><div className="inspector-facts"><b>{trace.evidence.length}<small>EVIDENCE ITEMS</small></b><b>{risk?risk.band:'—'}<small>RISK OVERLAY</small></b></div><small className="muted">Risk overlay is available only when a persisted assessment exists. It does not alter observed graph facts.</small></div>}
function InspectorHeading({eyebrow,title,badge}:{eyebrow:string;title:string;badge:string}){return <div className="inspector-heading"><div className="eyebrow">{eyebrow}</div><h2>{title}</h2><span className="data-badge">{badge}</span></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="graph-metric"><span>{label}</span><b>{value}</b></div>}
