import {useEffect,useState} from 'react';
import {api,apiUrl,syntheticStatus} from '../api';
import type {Case,Pattern,RiskAssessment,RealtimeAlert,TimelineEvent} from '../types';
const streamUrl=(caseId:string)=>`${apiUrl('/api/v1/realtime/stream')}?case_id=${encodeURIComponent(caseId)}`;
export function LiveIntelligence(){
 const [caseData,setCaseData]=useState<Case|null>(null);const [risk,setRisk]=useState<RiskAssessment|null>(null);const [patterns,setPatterns]=useState<Pattern[]>([]);const [alerts,setAlerts]=useState<RealtimeAlert[]>([]);const [timeline,setTimeline]=useState<TimelineEvent[]>([]);const [error,setError]=useState('');const [stream,setStream]=useState('CONNECTING');
 useEffect(()=>{let source:EventSource|undefined;let timer:number|undefined;let stopped=false;const load=async()=>{try{const state=await syntheticStatus();if(!state.case_id){setCaseData(null);setStream('WAITING');return}const loaded=await api.getCase(state.case_id);if(stopped)return;setCaseData(loaded);setRisk(await api.risk(state.case_id));if(loaded.latest_trace)setPatterns(await api.patterns(state.case_id,loaded.latest_trace.trace_id));setAlerts(await api.realtimeAlerts(state.case_id));setTimeline(await api.timeline(state.case_id));setError('');if(source)source.close();source=new EventSource(streamUrl(state.case_id));source.onopen=()=>setStream('CONNECTED');source.onerror=()=>setStream('RECONNECTING');const refresh=()=>load();for(const type of ['REALTIME_EVENT_RECEIVED','TRANSACTION_DETECTED','GRAPH_UPDATED','PATTERN_DETECTED','RISK_REASSESSED','ALERT_CREATED','EVIDENCE_CREATED'])source.addEventListener(type,refresh)}catch(e){setError(e instanceof Error?e.message:'Live intelligence unavailable');setStream('UNAVAILABLE')}};load();timer=window.setInterval(load,15000);return()=>{stopped=true;if(source)source.close();if(timer)window.clearInterval(timer)}},[]);
 return <section className="live-intelligence"><div className="panel-title"><div><span className="eyebrow">EVENT → INTELLIGENCE → UI</span><h3>Investigation feedback loop</h3></div><span className={'stream-state '+stream.toLowerCase()}>{stream}</span></div>{error&&<div className="error" role="alert">{error}</div>}{!caseData?<div className="empty-state">Start or step a synthetic engine run to see persisted intelligence change here.</div>:<><div className="intel-metrics"><span>GRAPH EDGES<strong>{caseData.latest_trace?.metrics.edge_count||0}</strong></span><span>PATTERNS<strong>{patterns.length}</strong></span><span>RISK<strong>{risk?.score??'—'} <small>{risk?.band||''}</small></strong></span><span>ALERTS<strong>{alerts.length}</strong></span><span>EVIDENCE<strong>{caseData.latest_trace?.evidence.length||0}</strong></span></div><div className="intel-flow"><span>EVENT RECEIVED</span><b>→</b><span>NORMALIZED</span><b>→</b><span>PERSISTED</span><b>→</b><span>GRAPH UPDATED</span><b>→</b><span>PATTERN / RISK</span><b>→</b><span className={alerts.length?'alert-flow':''}>ALERT / EVIDENCE</span></div><div className="intel-columns"><div><label>RISK DELTA</label><strong className={risk?.delta&&risk.delta.delta>0?'delta-up':''}>{risk?.delta?`${risk.delta.previous_score??'—'} → ${risk.delta.current_score} (${risk.delta.delta>=0?'+':''}${risk.delta.delta})`:'No reassessment delta yet'}</strong>{risk?.delta?.new_factors.map(f=><small key={f}>New factor: {f}</small>)}</div><div><label>LATEST PERSISTED TIMELINE</label>{timeline.slice(0,3).map(item=><small key={item.event_id}>{new Date(item.timestamp).toLocaleTimeString()} · {item.event_type.replaceAll('_',' ')}</small>)}</div></div></>}</section>
}
