import {useState} from 'react';
import type {Case,Pattern,PatternSummary,Trace} from '../types';
import {api} from '../api';

function PanelTitle({eyebrow,title}:{eyebrow:string;title:string}){return <div className="panel-title"><div className="eyebrow">{eyebrow}</div><h3>{title}</h3></div>}
function Empty({label,text}:{label:string;text:string}){return <div className="empty-block"><span>◇</span><b>{label}</b><p>{text}</p></div>}

export function PatternsPage({caseData,trace,onNavigate}:{caseData:Case;trace:Trace;onNavigate:(route:string)=>void}){
 const [patterns,setPatterns]=useState<Pattern[]>([]); const [summary,setSummary]=useState<PatternSummary|null>(null); const [selected,setSelected]=useState<Pattern|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 async function load(run:boolean){setBusy(true);setError('');try{if(run) await api.analyzePatterns(caseData.case_id,trace.trace_id);const [items,totals]=await Promise.all([api.patterns(caseData.case_id,trace.trace_id),api.patternSummary(caseData.case_id,trace.trace_id)]);setPatterns(items);setSummary(totals);setSelected(items[0]||null)}catch(e){setError(e instanceof Error?e.message:'Pattern analysis unavailable')}finally{setBusy(false)}}
 return <><div className="page-header"><div><div className="eyebrow">CASEWORK / PATTERN INTELLIGENCE</div><h1>Behavioral observations</h1></div><button className="primary" type="button" onClick={()=>load(true)} disabled={busy}>{busy?'Analyzing bounded trace…':'Analyze trace'}</button></div><div className="api-notice"><span className="ok-dot"/> OBSERVED BEHAVIOR ONLY · No risk score or criminality conclusion is generated.</div>{error&&<div className="error" role="alert">{error}</div>}<div className="pattern-summary-grid">{[['OBSERVATIONS',summary?.total_patterns??'—'],['HIGH',summary?.high_count??'—'],['MEDIUM',summary?.medium_count??'—'],['LOW / INFO',summary?((summary.by_severity.LOW||0)+(summary.by_severity.INFO||0)):'—']].map(item=><div className="metric-card" key={item[0]}><span>{item[0]}</span><b>{item[1]}</b><small>Evidence-backed observation</small></div>)}</div><div className="pattern-layout"><section className="surface"><PanelTitle eyebrow="ACTIVE BEHAVIORAL OBSERVATIONS" title={patterns.length?patterns.length+' observations':'No analysis loaded'}/>{!patterns.length?<Empty label="Run bounded pattern analysis" text="Pattern detection is explicit and operates only on the selected persisted trace."/>:<div className="pattern-list">{patterns.map(pattern=><button type="button" className={selected?.pattern_id===pattern.pattern_id?'pattern-card selected':'pattern-card'} key={pattern.pattern_id} onClick={()=>setSelected(pattern)}><span className={'badge '+pattern.severity.toLowerCase()}>{pattern.severity}</span><strong>{pattern.pattern_type.replaceAll('_',' ')}</strong><p>{pattern.description}</p><small>{pattern.transaction_hashes.length} transactions · {pattern.evidence_ids.length} evidence links</small></button>)}</div>}</section><aside className="surface pattern-detail">{selected?<><PanelTitle eyebrow="PATTERN INTELLIGENCE" title={selected.pattern_type.replaceAll('_',' ')}/><div className="detail-badges"><span className="badge blue">{selected.status}</span><span className="badge neutral">{selected.confidence_level} CONFIDENCE</span></div><dl><dt>SEVERITY</dt><dd>{selected.severity}</dd><dt>OBSERVATION</dt><dd>{selected.description}</dd><dt>EXPLANATION</dt><dd>{selected.explanation}</dd><dt>TRANSACTIONS</dt><dd className="mono">{selected.transaction_hashes.join(', ')}</dd><dt>EVIDENCE</dt><dd>{selected.evidence_ids.length} linked observation(s)</dd></dl><button className="secondary wide" type="button" onClick={()=>onNavigate('graph')}>Open graph workspace →</button></>:<Empty label="Select an observation" text="Pattern explanations and evidence links will appear here."/>}</aside></div></>
}
