import {useEffect,useState} from 'react';
import {api} from '../api';
import type {Case,Trace,Watch,TimelineEvent,ChangeSet,RealtimeAlert,Capability} from '../types';

export function RealtimePage({caseData,trace}:{caseData:Case;trace:Trace}){
 const [watches,setWatches]=useState<Watch[]>([]); const [timeline,setTimeline]=useState<TimelineEvent[]>([]); const [changes,setChanges]=useState<ChangeSet[]>([]); const [alerts,setAlerts]=useState<RealtimeAlert[]>([]); const [caps,setCaps]=useState<Capability[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const refresh=()=>Promise.all([api.watches(caseData.case_id),api.timeline(caseData.case_id),api.changes(caseData.case_id),api.realtimeAlerts(caseData.case_id),api.realtimeCapabilities()]).then(([w,t,c,a,p])=>{setWatches(w);setTimeline(t);setChanges(c);setAlerts(a);setCaps(p)}).catch(e=>setError(e.message));
 useEffect(()=>{refresh()},[caseData.case_id]);
 const capability=caps.find(c=>c.name==='address_activity_webhooks'); const configured=capability?.status==='SUPPORTED';
 async function start(){setBusy(true);setError('');try{await api.createWatch(caseData.case_id,trace.root_address);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function toggle(w:Watch){try{if(w.status==='ACTIVE')await api.pauseWatch(caseData.case_id,w.watch_id);else await api.resumeWatch(caseData.case_id,w.watch_id);await refresh()}catch(e){setError((e as Error).message)}}
 return <><div className="page-header"><div><div className="eyebrow">RRR / REAL-TIME RETRACING</div><h1>Monitoring command center</h1><p className="muted">Case-scoped event processing with explicit provider capability status.</p></div><span className={configured?'status-pill good':'status-pill warn'}>{configured?'LIVE WEBHOOK READY':'NOT CONFIGURED'}</span></div>
 <div className="monitor-banner"><div><span className="eyebrow">DATA MODE</span><strong>{configured?'LIVE':'HISTORICAL'}</strong><small>Alchemy Address Activity Webhook · Ethereum</small></div><div><span className="eyebrow">REAL-TIME ENGINE</span><strong>{configured?'READY':'NOT CONFIGURED'}</strong><small>Simulated intake remains available only as an explicit test seam.</small></div></div>
 <div className="monitor-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">WATCH TARGETS</span><h2>Tracked addresses</h2></div><button className="primary-button" disabled={busy||!configured} onClick={start}>{busy?'Starting…':'Watch root wallet'}</button></div>{!watches.length?<div className="empty-state">No watch targets exist for this case. A watch will only become active when the Alchemy webhook is configured.</div>:watches.map(w=><div className="watch-row" key={w.watch_id}><div><strong>{w.address.slice(0,10)}…{w.address.slice(-8)}</strong><small>{w.chain} · {w.provider}</small></div><span className={'status-pill '+(w.status==='ACTIVE'?'good':'warn')}>{w.status}</span><button className="ghost-button" onClick={()=>toggle(w)}>{w.status==='ACTIVE'?'Pause':'Resume'}</button>{w.error&&<small className="error-text">{w.error}</small>}</div>)}</section>
 <section className="panel"><div className="panel-head"><div><span className="eyebrow">INVESTIGATION TIMELINE</span><h2>Observed changes</h2></div></div>{!timeline.length?<div className="empty-state">No realtime observations have been applied.</div>:timeline.slice(0,8).map(e=><div className="timeline-row" key={e.event_id}><time>{new Date(e.timestamp).toLocaleTimeString()}</time><div><strong>{e.event_type.replaceAll('_',' ')}</strong><p>{e.summary}</p><small>{e.source}</small></div></div>)}</section></div>
 <div className="monitor-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">CHANGE SETS</span><h2>Graph and evidence updates</h2></div></div>{!changes.length?<div className="empty-state">The ledger will show before/after state once an event is applied.</div>:changes.map(c=><div className="change-row" key={c.change_set_id}><span className="signal-dot"/><div><strong>{String(c.changes.transactions_added||0)} transaction(s) added</strong><small>Event {c.event_id.slice(0,12)}… · edge {String(c.changes.graph_edge_id||'not created')}</small></div></div>)}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">ALERT CANDIDATES</span><h2>Review queue</h2></div></div>{!alerts.length?<div className="empty-state">No realtime alert candidates. Alerts are generated only after a persisted evidence-backed reassessment.</div>:alerts.map(a=><div className="alert-row" key={a.alert_id}><span className="status-pill warn">{a.severity}</span><div><strong>{a.title}</strong><p>{a.explanation}</p><small>Δ {a.risk_delta.toFixed(1)} · {a.status}</small></div></div>)}</section></div>
 </>
}
