import {useEffect,useState} from 'react';
import type {Case,InvestigationReport} from '../types';
import {createReport,downloadReportPdf,listReports} from '../api';

export function ReportsPage({caseData,trace}:{caseData:Case|null;trace?:{trace_id:string}}){
  const [items,setItems]=useState<InvestigationReport[]>([]); const [selected,setSelected]=useState<InvestigationReport|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [pdfBusy,setPdfBusy]=useState(false);
  useEffect(()=>{if(caseData)listReports(caseData.case_id).then(setItems).catch(e=>setError(e instanceof Error?e.message:'Reports unavailable'))},[caseData]);
  async function generate(){if(!caseData)return;setBusy(true);setError('');try{const item=await createReport(caseData.case_id,'INVESTIGATION_SUMMARY',trace?.trace_id);setItems(current=>[item,...current]);setSelected(item)}catch(e){setError(e instanceof Error?e.message:'Report generation failed')}finally{setBusy(false)}}
  async function download(){if(!caseData||!selected)return;setPdfBusy(true);setError('');try{await downloadReportPdf(caseData.case_id,selected.report_id)}catch(e){setError(e instanceof Error?e.message:'PDF export failed')}finally{setPdfBusy(false)}}
  return <><div className="page-header"><div><div className="eyebrow">CASEWORK / REPORTS</div><h1>Investigation reports</h1></div>{caseData&&<button className="primary" disabled={busy} onClick={generate}>{busy?'Building snapshot...':'Generate evidence-backed report'}</button>}</div>{!caseData?<div className="surface"><div className="empty-block"><b>No active case context</b><p>Open or create an investigation before generating a report.</p></div></div>:<><section className="surface"><div className="panel-title"><div className="eyebrow">PERSISTED REPORT SNAPSHOTS</div><h3>{items.length?items.length+' reports':'No reports generated'}</h3></div>{error&&<div className="error" role="alert">{error}</div>}{items.length?<div className="case-table">{items.map(item=><button className="case-row report-row" key={item.report_id} onClick={()=>setSelected(item)}><strong>{item.title}</strong><span>{item.report_type}</span><span>{item.evidence_ids.length} evidence</span><small>{new Date(item.created_at).toLocaleString()}</small></button>)}</div>:<div className="empty-block"><b>No persisted report snapshots</b><p>Reports are generated from persisted observations and retain evidence references.</p></div>}</section>{selected&&<section className="surface report-preview"><div className="report-preview-head"><div className="panel-title"><div className="eyebrow">REPORT PREVIEW | {selected.content_hash.slice(0,12)}</div><h3>{selected.title}</h3></div><button className="secondary" disabled={pdfBusy} onClick={download}>{pdfBusy?'Preparing PDF...':'Download PDF'}</button></div><div className="report-callout"><b>Complete blockchain cybersecurity dossier</b><span>Chain observations, fund-flow analysis, attribution, sanctions, threat intelligence, patterns, risk, alerts, evidence integrity, provenance, controls, and limitations.</span></div><pre>{selected.content}</pre><small>Evidence references: {selected.evidence_ids.join(', ')||'none'} | This is an investigative work product, not a legal filing.</small></section>}</>}</>
}
