import {useEffect,useMemo,useState} from 'react';
import {api} from '../api';
import type {CaseTransaction} from '../types';

const short=(value?:string)=>value&&value.length>18?`${value.slice(0,10)}...${value.slice(-6)}`:(value||'Unavailable');
const explorer=(chain:string,hash:string)=>chain==='ethereum'?`https://etherscan.io/tx/${hash}`:undefined;

export function TransactionLedger({caseId,onOpenGraph}:{caseId:string;onOpenGraph:(txHash?:string)=>void}){
 const [items,setItems]=useState<CaseTransaction[]>([]),[query,setQuery]=useState(''),[asset,setAsset]=useState('ALL'),[sort,setSort]=useState<'newest'|'amount'|'risk'>('newest'),[selected,setSelected]=useState<CaseTransaction|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{setLoading(true);setError('');api.transactions(caseId).then(setItems).catch(e=>setError(e instanceof Error?e.message:'Transaction ledger unavailable')).finally(()=>setLoading(false))},[caseId]);
 const assets=useMemo(()=>['ALL',...Array.from(new Set(items.map(item=>item.asset)))],[items]);
 const filtered=useMemo(()=>items.filter(item=>(asset==='ALL'||item.asset===asset)&&`${item.tx_hash} ${item.from_address} ${item.to_address} ${item.pattern_observations.map(p=>p.pattern_type).join(' ')} ${item.entity_exposure.map(e=>e.name).join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='risk'?b.risk_score-a.risk_score:sort==='amount'?Number(b.amount)-Number(a.amount):String(b.timestamp||'').localeCompare(String(a.timestamp||''))),[items,asset,query,sort]);
 return <section className="ledger-workspace"><header className="ledger-header"><div><span className="eyebrow">CASE / CANONICAL TRANSACTION LEDGER</span><h1>Observed blockchain activity</h1><p>Rows are read from persisted transaction, transfer, evidence, pattern, attribution, and risk-factor records.</p></div><div className="ledger-count"><b>{items.length}</b><small>PERSISTED TRANSFERS</small></div></header><div className="ledger-tools"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search transaction, address, pattern, or entity"/><select value={asset} onChange={event=>setAsset(event.target.value)}>{assets.map(value=><option key={value}>{value}</option>)}</select><select value={sort} onChange={event=>setSort(event.target.value as 'newest'|'amount'|'risk')}><option value="newest">Newest observed</option><option value="amount">Largest amount</option><option value="risk">Highest transaction risk</option></select><button className="secondary" onClick={()=>onOpenGraph()}>OPEN GRAPH</button></div>{error?<div className="error" role="alert">{error}</div>:loading?<div className="ledger-empty">Loading persisted ledger...</div>:!filtered.length?<div className="ledger-empty">No persisted transaction matches this filter.</div>:<div className="ledger-table"><div className="ledger-row ledger-head"><span>TRANSACTION</span><span>FLOW</span><span>ASSET / AMOUNT</span><span>RISK</span><span>PATTERN / ENTITY</span><span>EVIDENCE</span></div>{filtered.map(item=><button className="ledger-row" key={`${item.transaction_id}-${item.asset}-${item.amount}`} onClick={()=>setSelected(item)}><span><b className="mono">{short(item.tx_hash)}</b><small>{item.chain} | block {item.block_number??'--'} | {item.status}</small></span><span className="mono">{short(item.from_address)} <i>-&gt;</i> {short(item.to_address)}</span><span><b>{item.amount} {item.asset}</b><small>{item.transfer_type}</small></span><span><b className={`risk-band ${item.risk_band.toLowerCase()}`}>{item.risk_band}</b><small>{item.risk_score}/100 | {item.risk_factors.length} factor(s)</small></span><span><b>{item.pattern_observations[0]?.pattern_type?.replaceAll('_',' ')||'No pattern'}</b><small>{item.entity_exposure[0]?.name||'No entity exposure'}</small></span><span>{item.evidence_ids.length} record{item.evidence_ids.length===1?'':'s'}</span></button>)}</div>}{selected&&<TransactionDrawer item={selected} close={()=>setSelected(null)} onOpenGraph={onOpenGraph}/>}</section>
}

function TransactionDrawer({item,close,onOpenGraph}:{item:CaseTransaction;close:()=>void;onOpenGraph:(txHash?:string)=>void}){
 const link=explorer(item.chain,item.tx_hash);
 return <aside className="transaction-drawer" aria-label="Transaction intelligence"><div className="drawer-head"><div><span className="eyebrow">TRANSACTION INTELLIGENCE</span><h2>{item.amount} {item.asset}</h2></div><button onClick={close}>x</button></div><dl><dt>TRANSACTION HASH</dt><dd className="mono">{item.tx_hash}</dd><dt>CHAIN / BLOCK</dt><dd>{item.chain.toUpperCase()} | {item.block_number??'Unavailable'}</dd><dt>TIMESTAMP</dt><dd>{item.timestamp?new Date(item.timestamp).toLocaleString():'Unavailable'}</dd><dt>FROM</dt><dd className="mono">{item.from_address}</dd><dt>TO</dt><dd className="mono">{item.to_address}</dd><dt>TRANSFER</dt><dd>{item.transfer_type} | {item.amount} {item.asset}</dd><dt>CONTRACT / TOKEN</dt><dd className="mono">{item.contract_address||'Not applicable'}{item.token_id?` | token ${item.token_id}`:''}</dd><dt>PROVIDER</dt><dd>{item.provider}</dd><dt>TRANSACTION RISK</dt><dd><span className={`risk-band ${item.risk_band.toLowerCase()}`}>{item.risk_band}</span> {item.risk_score}/100</dd><dt>RISK OBSERVATIONS</dt><dd>{item.risk_factors.length?item.risk_factors.map(f=><span className="factor-chip risk-high" key={f.factor_id}>{f.name} +{f.contribution} | {f.confidence_level}</span>):'No direct risk factor linked to this transaction.'}</dd><dt>PATTERN OBSERVATIONS</dt><dd>{item.pattern_observations.length?item.pattern_observations.map(p=><span className="factor-chip" key={p.pattern_id}>{p.pattern_type.replaceAll('_',' ')} | {p.severity}</span>):'No persisted pattern observation linked.'}</dd><dt>ENTITY / VASP OBSERVATIONS</dt><dd>{item.entity_exposure.length?item.entity_exposure.map(e=><span className="factor-chip" key={`${e.entity_id}-${e.address}`}>{e.name} | {e.entity_type} | {e.confidence}</span>):'No source-backed attribution on this transfer.'}</dd><dt>EVIDENCE REFERENCES</dt><dd>{item.evidence_ids.join(', ')||'No evidence link persisted'}</dd></dl><div className="drawer-actions"><button className="secondary" onClick={()=>navigator.clipboard?.writeText(item.tx_hash)}>COPY HASH</button><button className="secondary" onClick={()=>onOpenGraph(item.tx_hash)}>HIGHLIGHT GRAPH EDGE</button>{link&&<a className="secondary" href={link} target="_blank" rel="noreferrer">OPEN EXPLORER</a>}</div></aside>
}
