"""Fusion overlay generator — the core innovation of this build.

=============================================================================
HONESTY NOTICE — READ BEFORE USING THESE NUMBERS IN A DEMO OR DECK
=============================================================================
No public dataset links a real user's cyber/login events to their fraud
transactions. That gap IS the market gap this project targets. This script
does NOT join real bank data to real SIEM data — it SYNTHESIZES the link on
top of PaySim as a controlled, fully-reproducible evaluation harness so we
can measure whether a fused engine recovers frauds a tabular-only model
would miss, when a cyber precursor exists. Every "compromise event" here is
generated by this script, not observed. Present it to judges exactly this
way (see Docs/ Judge Q&A #1).
=============================================================================

Pipeline:
  1. Load PaySim from data/raw, filter to TRANSFER + CASH_OUT (where PaySim fraud
     concentrates), sample down to a manageable size while keeping ALL fraud rows.
  2. Assign every account a synthetic identity (user_id, device_id, ip, home geo).
     A subset of destination (beneficiary) accounts are deliberately grouped into
     mule clusters that share a device/IP, to create detectable ring structure.
  3. Generate a per-user cyber event log: mostly normal logins, plus injected
     compromise sequences (impossible-travel login, new-device + MFA-cookie
     reuse, credential-stuffing success) inspired by UNSW-NB15 attack categories.
  4. For a configurable slice of fraud transactions, place a compromise event
     30-120s before the fraud. The rest of the frauds get no preceding cyber
     signal, so fusion uplift is measurable rather than universal by construction.
  5. Compute `cyber_compromise_in_window` for every transaction: True if a
     compromise event for that transaction's user fired within a configurable
     window (default 300s) before it.
  6. Write data/processed/transactions.csv, data/processed/fused_events.csv, and
     data/processed/overlay_report.md.

Fully reproducible: one fixed RANDOM_SEED, all knobs live in the CONFIG block below.

Usage:
    python data/build_overlay.py
"""

from __future__ import annotations

import math
import random
from pathlib import Path

import numpy as np
import pandas as pd

# =============================================================================
# CONFIG — every tunable knob lives here, nowhere else in the file.
# =============================================================================

RANDOM_SEED = 42

RAW_DIR = Path(__file__).parent / "raw"
PROCESSED_DIR = Path(__file__).parent / "processed"

# PaySim fraud lives almost entirely in these two transaction types.
KEPT_TXN_TYPES = ("TRANSFER", "CASH_OUT")

# Cap total kept transactions for a manageable demo-scale dataset. All fraud rows
# are always kept; only non-fraud rows are subsampled down to hit this cap.
MAX_TOTAL_TRANSACTIONS = 400_000

# PaySim's `step` column is hours-since-start (1..743). We map it onto a real
# calendar so events can carry second-level timestamps.
BASE_TIMESTAMP = pd.Timestamp("2026-01-05T00:00:00")

# Mule-ring structure: a subset of beneficiary (destination) accounts are grouped
# into clusters that share one device_id + one IP, biased towards accounts that
# actually receive fraud money so the ring is visible in the demo's threat graph.
MULE_CLUSTER_SIZE = 6
N_MULE_CLUSTERS = 10

# Of the fraud transactions, this fraction get a cyber-compromise event placed
# 30-120s before them. The rest are left as "silent" frauds with no cyber
# precursor -- this is what makes fusion uplift a measurable delta, not 100%.
CYBER_PRECEDED_FRAUD_FRACTION = 0.45
COMPROMISE_LEAD_TIME_SECONDS = (30, 120)

# Default pre-window (seconds) used to compute cyber_compromise_in_window.
# Kept configurable because the risk engine (Prompt 3) may want to tune it.
DEFAULT_FUSION_WINDOW_SECONDS = 300

# Compromise event "flavors", inspired by UNSW-NB15 attack categories, and their
# relative weight when picking which one to inject before a chosen fraud.
COMPROMISE_EVENT_TYPES = {
    "impossible_travel_login": 0.45,
    "new_device_mfa_cookie_reuse": 0.30,
    "credential_stuffing_success": 0.25,
}

# A small fraction of users who are NOT part of the chosen cyber-preceded fraud
# slice still get an unrelated compromise event somewhere in the timeline. This
# is deliberate realism: a SOC generates alerts that never correlate with fraud,
# so cyber_compromise_in_window must not become a trivial proxy for isFraud.
NOISE_COMPROMISE_USER_FRACTION = 0.03

# Normal login volume per user over the observation window (Poisson mean).
NORMAL_LOGINS_PER_USER_MEAN = 4

# Baseline "home" geo is sampled uniformly inside a rough India bounding box
# (this is a bank-of-Maharashtra-flavored demo, not a claim about real user
# locations).
INDIA_LAT_RANGE = (8.0, 35.0)
INDIA_LON_RANGE = (68.0, 97.0)

# Distance bands (km from baseline) used per event flavor.
NORMAL_LOGIN_JITTER_KM = (0.0, 5.0)
IMPOSSIBLE_TRAVEL_KM = (1500.0, 9000.0)
NEW_DEVICE_LOCAL_KM = (0.0, 80.0)
STUFFING_KM = (0.0, 6000.0)

EARTH_RADIUS_KM = 6371.0


# =============================================================================
# Helpers
# =============================================================================


def set_seeds(seed: int) -> np.random.Generator:
    random.seed(seed)
    np.random.seed(seed)
    return np.random.default_rng(seed)


def haversine_km(lat1, lon1, lat2, lon2) -> float:
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    dlat, dlon = lat2 - lat1, lon2 - lon1
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    return 2 * EARTH_RADIUS_KM * math.asin(math.sqrt(a))


def random_point_at_distance(lat, lon, distance_km, rng) -> tuple[float, float]:
    """Return a lat/lon roughly `distance_km` away from (lat, lon), random bearing."""
    bearing = rng.uniform(0, 2 * math.pi)
    ang_dist = distance_km / EARTH_RADIUS_KM
    lat1, lon1 = math.radians(lat), math.radians(lon)
    lat2 = math.asin(
        math.sin(lat1) * math.cos(ang_dist) + math.cos(lat1) * math.sin(ang_dist) * math.cos(bearing)
    )
    lon2 = lon1 + math.atan2(
        math.sin(bearing) * math.sin(ang_dist) * math.cos(lat1),
        math.cos(ang_dist) - math.sin(lat1) * math.sin(lat2),
    )
    return math.degrees(lat2), math.degrees(lon2)


def random_ip(rng) -> str:
    return ".".join(str(int(rng.integers(1, 255))) for _ in range(4))


def random_device_id(rng) -> str:
    return "dev_" + "".join(rng.choice(list("0123456789abcdef")) for _ in range(12))


# =============================================================================
# Step 1: load + sample PaySim
# =============================================================================


def find_paysim_csv() -> Path:
    candidates = sorted(RAW_DIR.glob("**/*.csv"))
    paysim_candidates = [
        p for p in candidates
        if "paysim" in str(p).lower() or "ps_2017" in p.name.lower() or "PS_2017" in p.name
    ]
    if not paysim_candidates:
        # Fall back to the biggest CSV in raw/, which is almost always PaySim's.
        if not candidates:
            raise FileNotFoundError(
                f"No CSV files found under {RAW_DIR}. Run `python data/download.py` first."
            )
        paysim_candidates = [max(candidates, key=lambda p: p.stat().st_size)]
    return paysim_candidates[0]


def load_paysim(rng: np.random.Generator) -> pd.DataFrame:
    csv_path = find_paysim_csv()
    print(f"-> Loading PaySim from {csv_path}")
    df = pd.read_csv(csv_path)

    df = df[df["type"].isin(KEPT_TXN_TYPES)].copy()
    print(f"   {len(df):,} rows after filtering to {KEPT_TXN_TYPES}")

    fraud_df = df[df["isFraud"] == 1]
    nonfraud_df = df[df["isFraud"] == 0]
    print(f"   {len(fraud_df):,} fraud rows (always kept), {len(nonfraud_df):,} non-fraud rows")

    budget_nonfraud = max(MAX_TOTAL_TRANSACTIONS - len(fraud_df), 0)
    if len(nonfraud_df) > budget_nonfraud:
        nonfraud_df = nonfraud_df.sample(n=budget_nonfraud, random_state=RANDOM_SEED)
        print(f"   Sampled non-fraud rows down to {len(nonfraud_df):,} to respect "
              f"MAX_TOTAL_TRANSACTIONS={MAX_TOTAL_TRANSACTIONS:,}")

    out = pd.concat([fraud_df, nonfraud_df], ignore_index=True)
    out = out.sort_values("step").reset_index(drop=True)
    out["txn_id"] = [f"txn_{i:07d}" for i in range(len(out))]
    print(f"   Final kept transaction count: {len(out):,} "
          f"({out['isFraud'].sum():,} fraud, {out['isFraud'].mean() * 100:.3f}% fraud rate)")
    return out


# =============================================================================
# Step 2: synthetic identities + mule clusters
# =============================================================================


def build_identity_table(accounts: list[str], rng: np.random.Generator) -> pd.DataFrame:
    """One synthetic identity per unique PaySim account id (nameOrig/nameDest)."""
    n = len(accounts)
    lats = rng.uniform(*INDIA_LAT_RANGE, size=n)
    lons = rng.uniform(*INDIA_LON_RANGE, size=n)
    identity = pd.DataFrame({
        "account_id": accounts,
        "user_id": [f"usr_{i:06d}" for i in range(n)],
        "device_id": [random_device_id(rng) for _ in range(n)],
        "ip": [random_ip(rng) for _ in range(n)],
        "home_lat": lats,
        "home_lon": lons,
        "mule_cluster_id": pd.array([None] * n, dtype="object"),
    })
    return identity


def assign_mule_clusters(
    identity: pd.DataFrame,
    preferred_accounts: list[str],
    rng: np.random.Generator,
) -> pd.DataFrame:
    """Group a subset of accounts into device/IP-sharing mule clusters.

    Preferred accounts (fraud beneficiaries) are used first so the ring
    structure is actually visible on the transactions that matter for the demo;
    if there aren't enough of them, random accounts pad out the clusters.
    """
    identity = identity.set_index("account_id")
    needed = N_MULE_CLUSTERS * MULE_CLUSTER_SIZE

    pool = list(dict.fromkeys(preferred_accounts))  # de-dup, keep order
    rng.shuffle(pool)
    if len(pool) < needed:
        remaining = list(set(identity.index) - set(pool))
        rng.shuffle(remaining)
        pool = pool + remaining[: needed - len(pool)]
    pool = pool[:needed]

    for cluster_idx in range(N_MULE_CLUSTERS):
        members = pool[cluster_idx * MULE_CLUSTER_SIZE : (cluster_idx + 1) * MULE_CLUSTER_SIZE]
        if not members:
            continue
        cluster_id = f"mule_{cluster_idx:03d}"
        shared_device = random_device_id(rng)
        shared_ip = random_ip(rng)
        # Anchor the cluster's shared baseline geo to the first member's location.
        anchor_lat = identity.loc[members[0], "home_lat"]
        anchor_lon = identity.loc[members[0], "home_lon"]
        for acc in members:
            identity.loc[acc, "device_id"] = shared_device
            identity.loc[acc, "ip"] = shared_ip
            identity.loc[acc, "home_lat"] = anchor_lat
            identity.loc[acc, "home_lon"] = anchor_lon
            identity.loc[acc, "mule_cluster_id"] = cluster_id

    return identity.reset_index()


# =============================================================================
# Step 3-4: timestamps + cyber event log
# =============================================================================


def assign_timestamps(txns: pd.DataFrame, rng: np.random.Generator) -> pd.DataFrame:
    """PaySim's `step` is hours-since-start; add random within-hour jitter so
    transactions get distinct second-level timestamps (needed for a 30-120s
    pre-fraud compromise window to mean anything)."""
    jitter_seconds = rng.integers(0, 3600, size=len(txns))
    txns = txns.copy()
    txns["timestamp"] = BASE_TIMESTAMP + pd.to_timedelta(txns["step"], unit="h") + pd.to_timedelta(
        jitter_seconds, unit="s"
    )
    return txns


def random_points_at_distance_vec(lat, lon, distance_km, rng: np.random.Generator):
    """Vectorized form of random_point_at_distance for bulk login generation."""
    n = len(lat)
    bearing = rng.uniform(0, 2 * np.pi, size=n)
    ang_dist = distance_km / EARTH_RADIUS_KM
    lat1, lon1 = np.radians(lat), np.radians(lon)
    lat2 = np.arcsin(
        np.sin(lat1) * np.cos(ang_dist) + np.cos(lat1) * np.sin(ang_dist) * np.cos(bearing)
    )
    lon2 = lon1 + np.arctan2(
        np.sin(bearing) * np.sin(ang_dist) * np.cos(lat1),
        np.cos(ang_dist) - np.sin(lat1) * np.sin(lat2),
    )
    return np.degrees(lat2), np.degrees(lon2)


def make_normal_login_events(
    identity: pd.DataFrame, txns: pd.DataFrame, rng: np.random.Generator
) -> pd.DataFrame:
    """A handful of ordinary logins per user, scattered across the observation
    window, near the user's home geo/device/IP. Vectorized: identity tables here
    run into the hundreds of thousands of rows, and a Python-level loop over
    every (user, login) pair is the dominant cost of the whole generator."""
    span_start = txns["timestamp"].min()
    span_end = txns["timestamp"].max()
    span_seconds = max(int((span_end - span_start).total_seconds()), 1)

    n_logins = rng.poisson(NORMAL_LOGINS_PER_USER_MEAN, size=len(identity))
    total = int(n_logins.sum())
    if total == 0:
        return pd.DataFrame(columns=[
            "timestamp", "user_id", "device_id", "ip", "event_type",
            "geo_lat", "geo_lon", "km_from_baseline", "severity", "related_txn_id",
        ])

    repeat_idx = np.repeat(np.arange(len(identity)), n_logins)
    home_lat = identity["home_lat"].to_numpy()[repeat_idx]
    home_lon = identity["home_lon"].to_numpy()[repeat_idx]

    offsets = rng.integers(0, span_seconds, size=total)
    dist_km = rng.uniform(*NORMAL_LOGIN_JITTER_KM, size=total)
    lat, lon = random_points_at_distance_vec(home_lat, home_lon, dist_km, rng)

    return pd.DataFrame({
        "timestamp": span_start + pd.to_timedelta(offsets, unit="s"),
        "user_id": identity["user_id"].to_numpy()[repeat_idx],
        "device_id": identity["device_id"].to_numpy()[repeat_idx],
        "ip": identity["ip"].to_numpy()[repeat_idx],
        "event_type": "login_normal",
        "geo_lat": lat,
        "geo_lon": lon,
        "km_from_baseline": np.round(dist_km, 2),
        "severity": "info",
        "related_txn_id": None,
    })


def make_compromise_event(
    ident_row: pd.Series, txn_timestamp: pd.Timestamp, kind: str, rng: np.random.Generator,
    related_txn_id: str | None,
) -> list[dict]:
    """Build the compromise event (or short sequence, for credential stuffing)
    that fires shortly before `txn_timestamp`."""
    lead_s = int(rng.integers(*COMPROMISE_LEAD_TIME_SECONDS))
    event_ts = txn_timestamp - pd.Timedelta(seconds=lead_s)
    home_lat, home_lon = ident_row["home_lat"], ident_row["home_lon"]

    if kind == "impossible_travel_login":
        dist_km = rng.uniform(*IMPOSSIBLE_TRAVEL_KM)
        lat, lon = random_point_at_distance(home_lat, home_lon, dist_km, rng)
        return [{
            "timestamp": event_ts,
            "user_id": ident_row["user_id"],
            "device_id": ident_row["device_id"],
            "ip": random_ip(rng),
            "event_type": "impossible_travel_login",
            "geo_lat": lat,
            "geo_lon": lon,
            "km_from_baseline": round(dist_km, 2),
            "severity": "critical",
            "related_txn_id": related_txn_id,
        }]

    if kind == "new_device_mfa_cookie_reuse":
        dist_km = rng.uniform(*NEW_DEVICE_LOCAL_KM)
        lat, lon = random_point_at_distance(home_lat, home_lon, dist_km, rng)
        return [{
            "timestamp": event_ts,
            "user_id": ident_row["user_id"],
            "device_id": random_device_id(rng),  # a device never seen before for this user
            "ip": ident_row["ip"],
            "event_type": "new_device_mfa_cookie_reuse",
            "geo_lat": lat,
            "geo_lon": lon,
            "km_from_baseline": round(dist_km, 2),
            "severity": "high",
            "related_txn_id": related_txn_id,
        }]

    if kind == "credential_stuffing_success":
        dist_km = rng.uniform(*STUFFING_KM)
        lat, lon = random_point_at_distance(home_lat, home_lon, dist_km, rng)
        attacker_ip = random_ip(rng)
        rows = []
        n_failed = int(rng.integers(2, 5))
        for i in range(n_failed, 0, -1):
            fail_ts = event_ts - pd.Timedelta(seconds=int(rng.integers(20, 90)) * i)
            rows.append({
                "timestamp": fail_ts,
                "user_id": ident_row["user_id"],
                "device_id": random_device_id(rng),
                "ip": attacker_ip,
                "event_type": "login_failed",
                "geo_lat": lat,
                "geo_lon": lon,
                "km_from_baseline": round(dist_km, 2),
                "severity": "medium",
                "related_txn_id": related_txn_id,
            })
        rows.append({
            "timestamp": event_ts,
            "user_id": ident_row["user_id"],
            "device_id": random_device_id(rng),
            "ip": attacker_ip,
            "event_type": "credential_stuffing_success",
            "geo_lat": lat,
            "geo_lon": lon,
            "km_from_baseline": round(dist_km, 2),
            "severity": "critical",
            "related_txn_id": related_txn_id,
        })
        return rows

    raise ValueError(f"Unknown compromise event kind: {kind}")


def choose_cyber_preceded_frauds(txns: pd.DataFrame, rng: np.random.Generator) -> pd.DataFrame:
    fraud_txns = txns[txns["isFraud"] == 1]
    n_selected = int(round(len(fraud_txns) * CYBER_PRECEDED_FRAUD_FRACTION))
    selected = fraud_txns.sample(n=n_selected, random_state=RANDOM_SEED)
    return selected


def generate_cyber_events(
    txns: pd.DataFrame, identity: pd.DataFrame, rng: np.random.Generator
) -> tuple[pd.DataFrame, pd.DataFrame]:
    identity_by_account = identity.set_index("account_id")

    # 1. Ordinary background login traffic for every identity that appears as an
    #    originator (the "logged-in" side of a transaction).
    orig_accounts = txns["nameOrig"].unique()
    orig_identity = identity[identity["account_id"].isin(orig_accounts)]
    normal_events_df = make_normal_login_events(orig_identity, txns, rng)
    rows = []

    # 2. Choose which frauds get a preceding compromise, and inject it.
    selected_frauds = choose_cyber_preceded_frauds(txns, rng)
    kinds = list(COMPROMISE_EVENT_TYPES.keys())
    weights = list(COMPROMISE_EVENT_TYPES.values())

    for _, txn in selected_frauds.iterrows():
        ident_row = identity_by_account.loc[txn["nameOrig"]]
        kind = rng.choice(kinds, p=weights)
        rows.extend(make_compromise_event(ident_row, txn["timestamp"], kind, rng, txn["txn_id"]))

    # 3. Noise: unrelated compromise events on users NOT in the selected slice,
    #    so cyber_compromise_in_window isn't a trivial stand-in for isFraud.
    selected_users = set(selected_frauds["nameOrig"])
    noise_candidates = [a for a in orig_accounts if a not in selected_users]
    n_noise = int(round(len(noise_candidates) * NOISE_COMPROMISE_USER_FRACTION))
    noise_accounts = rng.choice(noise_candidates, size=min(n_noise, len(noise_candidates)), replace=False)

    span_start, span_end = txns["timestamp"].min(), txns["timestamp"].max()
    span_seconds = max(int((span_end - span_start).total_seconds()), 1)
    for account in noise_accounts:
        ident_row = identity_by_account.loc[account]
        offset = rng.integers(0, span_seconds)
        noise_ts = span_start + pd.Timedelta(seconds=int(offset))
        kind = rng.choice(kinds, p=weights)
        rows.extend(make_compromise_event(ident_row, noise_ts, kind, rng, related_txn_id=None))

    events = pd.concat([normal_events_df, pd.DataFrame(rows)], ignore_index=True)
    events = events.sort_values("timestamp").reset_index(drop=True)
    events.insert(0, "event_id", [f"evt_{i:07d}" for i in range(len(events))])
    return events, selected_frauds


# =============================================================================
# Step 5: cyber_compromise_in_window feature
# =============================================================================

COMPROMISE_EVENT_KINDS = set(COMPROMISE_EVENT_TYPES.keys())


def compute_cyber_compromise_in_window(
    txns: pd.DataFrame, events: pd.DataFrame, window_seconds: int = DEFAULT_FUSION_WINDOW_SECONDS
) -> pd.Series:
    """For every transaction, True if a compromise-type event for that
    transaction's originating user fired within `window_seconds` before it.

    Requires txns["user_id"] to already hold the synthetic identity id (not the
    raw PaySim nameOrig) — that's what fused_events.csv's user_id column uses.
    """
    compromise_events = events[events["event_type"].isin(COMPROMISE_EVENT_KINDS)][
        ["user_id", "timestamp"]
    ].rename(columns={"timestamp": "event_timestamp"})

    if compromise_events.empty:
        return pd.Series(False, index=txns.index)

    left = txns[["txn_id", "user_id", "timestamp"]].copy()
    left = left.sort_values("timestamp")
    compromise_events = compromise_events.sort_values("event_timestamp")

    merged = pd.merge_asof(
        left,
        compromise_events,
        left_on="timestamp",
        right_on="event_timestamp",
        by="user_id",
        direction="backward",
        allow_exact_matches=False,
    )
    delta = (merged["timestamp"] - merged["event_timestamp"]).dt.total_seconds()
    in_window = delta.notna() & (delta >= 0) & (delta <= window_seconds)
    in_window.index = merged["txn_id"]
    return in_window.reindex(txns["txn_id"]).fillna(False).to_numpy()


# =============================================================================
# Step 6: report
# =============================================================================


def write_overlay_report(
    txns: pd.DataFrame,
    events: pd.DataFrame,
    identity: pd.DataFrame,
    selected_frauds: pd.DataFrame,
) -> None:
    n_fraud = int(txns["isFraud"].sum())
    n_cyber_preceded = len(selected_frauds)
    n_mule_clusters = identity["mule_cluster_id"].nunique(dropna=True)
    n_mule_accounts = identity["mule_cluster_id"].notna().sum()
    event_counts = events["event_type"].value_counts()

    lines = [
        "# Fusion Overlay Report",
        "",
        "> Synthetic correlation harness — see the honesty notice at the top of "
        "`data/build_overlay.py`. This is not real joined bank data.",
        "",
        f"- Random seed: `{RANDOM_SEED}`",
        f"- Transactions kept: {len(txns):,} (types: {', '.join(KEPT_TXN_TYPES)})",
        f"- Fraud transactions: {n_fraud:,} ({n_fraud / len(txns) * 100:.3f}% of kept transactions)",
        f"- Fraud transactions with a preceding cyber-compromise event: "
        f"{n_cyber_preceded:,} ({n_cyber_preceded / n_fraud * 100:.1f}% of fraud, "
        f"target was {CYBER_PRECEDED_FRAUD_FRACTION * 100:.0f}%)",
        f"- Fraud transactions with NO preceding cyber signal (silos-only would need to catch these "
        f"on tabular/graph signal alone): {n_fraud - n_cyber_preceded:,}",
        f"- Mule clusters: {n_mule_clusters} clusters, {n_mule_accounts} accounts "
        f"(~{MULE_CLUSTER_SIZE} accounts/cluster sharing one device + IP)",
        f"- Cyber events generated: {len(events):,}",
        "",
        "## Event-type distribution",
        "",
        "| event_type | count |",
        "|---|---|",
    ]
    for event_type, count in event_counts.items():
        lines.append(f"| {event_type} | {count:,} |")

    lines += [
        "",
        "## What this proves and doesn't prove",
        "",
        "- Proves: when a cyber-compromise precedes a fraudulent transfer within the fusion "
        "window, `cyber_compromise_in_window` reliably flags it — this is the signal the fusion "
        "risk engine (Prompt 3) will use, alongside tabular and graph features.",
        "- Does not prove: that this correlation exists in real bank data. It's a controlled "
        "evaluation harness demonstrating fusion uplift *when* the correlation is present.",
        f"- By construction, {CYBER_PRECEDED_FRAUD_FRACTION * 100:.0f}% of frauds have this "
        "precursor and the rest do not — so a model scoring 100% recall via this feature alone "
        "would still miss the silent frauds, same as it should in reality.",
    ]

    (PROCESSED_DIR / "overlay_report.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"-> Wrote {PROCESSED_DIR / 'overlay_report.md'}")


# =============================================================================
# Sanity check — previews the fusion-uplift story without training a real model
# =============================================================================


def sanity_check(txns: pd.DataFrame) -> None:
    """Tiny, dependency-light preview of fusion uplift.

    This is NOT the final metric (that's Prompt 2/3's job with a properly
    trained, held-out-evaluated model at a matched false-positive rate). It
    uses a naive log(amount) percentile as a stand-in "tabular-only" signal to
    show, directionally, that adding the cyber-context feature recovers
    cyber-preceded frauds the naive signal alone misses.
    """
    print("\n=== Sanity check: naive tabular-only vs. tabular+cyber-context ===")
    print("(naive heuristic preview only — see ml/metrics_report.md for the real numbers)")

    cyber_preceded = txns[txns["cyber_compromise_in_window"] & (txns["isFraud"] == 1)]
    silent_fraud = txns[~txns["cyber_compromise_in_window"] & (txns["isFraud"] == 1)]
    print(f"Cyber-preceded frauds: {len(cyber_preceded):,} | Silent frauds: {len(silent_fraud):,}")

    naive_score = np.log1p(txns["amount"])
    flag_threshold = naive_score.quantile(0.99)  # flag top 1% by naive amount score
    tabular_only_flag = naive_score >= flag_threshold
    fused_flag = tabular_only_flag | txns["cyber_compromise_in_window"]

    tabular_recall = tabular_only_flag[cyber_preceded.index].mean() if len(cyber_preceded) else float("nan")
    fused_recall = fused_flag[cyber_preceded.index].mean() if len(cyber_preceded) else float("nan")

    tabular_fp_rate = tabular_only_flag[txns["isFraud"] == 0].mean()
    fused_fp_rate = fused_flag[txns["isFraud"] == 0].mean()

    print(f"\nOn the {len(cyber_preceded):,} cyber-preceded frauds:")
    print(f"  naive tabular-only (top-1%-by-amount) recall : {tabular_recall * 100:.1f}%")
    print(f"  tabular + cyber-context recall                : {fused_recall * 100:.1f}%")
    print(f"  preview uplift                                : "
          f"+{(fused_recall - tabular_recall) * 100:.1f} points")
    print(f"\nFalse-positive rate on non-fraud transactions (not matched, preview only):")
    print(f"  naive tabular-only FP rate : {tabular_fp_rate * 100:.3f}%")
    print(f"  fused FP rate              : {fused_fp_rate * 100:.3f}%")
    print("\nThis previews the story; ml/metrics_report.md (Prompt 2/3) will report the real "
          "PR-AUC/F1/recall-at-fixed-FPR delta from trained models, at a matched operating point.")


# =============================================================================
# Main
# =============================================================================


def main() -> None:
    rng = set_seeds(RANDOM_SEED)
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

    txns = load_paysim(rng)
    txns = assign_timestamps(txns, rng)

    all_accounts = pd.unique(pd.concat([txns["nameOrig"], txns["nameDest"]], ignore_index=True))
    print(f"-> Building identity table for {len(all_accounts):,} unique accounts")
    identity = build_identity_table(list(all_accounts), rng)

    fraud_dest_accounts = txns.loc[txns["isFraud"] == 1, "nameDest"].tolist()
    identity = assign_mule_clusters(identity, fraud_dest_accounts, rng)

    identity_by_account = identity.set_index("account_id")
    txns["user_id"] = txns["nameOrig"].map(identity_by_account["user_id"])
    txns["device_id"] = txns["nameOrig"].map(identity_by_account["device_id"])
    txns["ip"] = txns["nameOrig"].map(identity_by_account["ip"])
    txns["dest_user_id"] = txns["nameDest"].map(identity_by_account["user_id"])
    txns["dest_device_id"] = txns["nameDest"].map(identity_by_account["device_id"])
    txns["dest_ip"] = txns["nameDest"].map(identity_by_account["ip"])
    txns["dest_mule_cluster_id"] = txns["nameDest"].map(identity_by_account["mule_cluster_id"])

    print("-> Generating cyber event log")
    events, selected_frauds = generate_cyber_events(txns, identity, rng)

    print("-> Computing cyber_compromise_in_window feature")
    txns["cyber_compromise_in_window"] = compute_cyber_compromise_in_window(
        txns, events, DEFAULT_FUSION_WINDOW_SECONDS
    )

    txn_cols = [
        "txn_id", "step", "timestamp", "type", "amount",
        "nameOrig", "user_id", "device_id", "ip",
        "oldbalanceOrg", "newbalanceOrig",
        "nameDest", "dest_user_id", "dest_device_id", "dest_ip", "dest_mule_cluster_id",
        "oldbalanceDest", "newbalanceDest",
        "isFraud", "isFlaggedFraud", "cyber_compromise_in_window",
    ]
    out_txns = txns[txn_cols].copy()

    event_cols = [
        "event_id", "timestamp", "user_id", "device_id", "ip", "event_type",
        "geo_lat", "geo_lon", "km_from_baseline", "severity", "related_txn_id",
    ]
    out_events = events[event_cols].copy()

    out_txns.to_csv(PROCESSED_DIR / "transactions.csv", index=False)
    print(f"-> Wrote {PROCESSED_DIR / 'transactions.csv'} ({len(out_txns):,} rows)")
    out_events.to_csv(PROCESSED_DIR / "fused_events.csv", index=False)
    print(f"-> Wrote {PROCESSED_DIR / 'fused_events.csv'} ({len(out_events):,} rows)")

    write_overlay_report(out_txns, out_events, identity, selected_frauds)

    sanity_check(out_txns)


if __name__ == "__main__":
    main()
