"""Provider-independent real-time event boundary and Alchemy webhook adapter."""
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from hashlib import sha256
import hashlib
import hmac
import re
from typing import Any

from .config import settings
from .domain import *

ADDRESS_RE=re.compile(r"^0x[0-9a-fA-F]{40}$")

class RealtimeProvider(ABC):
    name="unknown"
    @abstractmethod
    async def subscribe_to_address_activity(self,address:str,chain:Chain,watch_id:str)->WatchTarget: ...
    @abstractmethod
    async def unsubscribe(self,subscription_id:str)->None: ...
    @abstractmethod
    async def health(self)->dict: ...
    @abstractmethod
    def capabilities(self)->list[ProviderCapability]: ...

class AlchemyRealtimeAdapter(RealtimeProvider):
    name="Alchemy Address Activity Webhook"
    def configured(self): return bool(settings.alchemy_api_key and settings.alchemy_webhook_id and settings.alchemy_webhook_signing_key)
    def capabilities(self):
        status=CapabilityStatus.SUPPORTED if self.configured() else CapabilityStatus.NOT_CONFIGURED
        return [ProviderCapability(name="address_activity_webhooks",status=status,mode=DataMode.WEBHOOK,note="Alchemy Notify Address Activity webhook; configure webhook ID, signing key, and API key."),ProviderCapability(name="websocket",status=CapabilityStatus.UNSUPPORTED,mode=DataMode.SUBSCRIPTION,note="WebSocket event adapter is not enabled."),ProviderCapability(name="incremental_retracing",status=CapabilityStatus.SUPPORTED,mode=DataMode.WEBHOOK,note="Local event processing path is available when a provider webhook is configured."),ProviderCapability(name="realtime_alerts",status=CapabilityStatus.SUPPORTED,mode=DataMode.WEBHOOK,note="Evidence-backed internal alert candidates are generated by the processing service.")]
    async def subscribe_to_address_activity(self,address,chain,watch_id):
        status=WatchTargetStatus.ACTIVE if self.configured() else WatchTargetStatus.ERROR
        return WatchTarget(watch_id=watch_id,case_id="",address=address.lower(),chain=chain,source="INVESTIGATOR",created_at=datetime.now(timezone.utc),status=status,provider=self.name,subscription_id=settings.alchemy_webhook_id,error=None if status==WatchTargetStatus.ACTIVE else "Alchemy webhook configuration is incomplete")
    async def unsubscribe(self,subscription_id): return None
    async def health(self): return {"provider":self.name,"status":"HEALTHY" if self.configured() else "NOT_CONFIGURED","webhook":"CONFIGURED" if self.configured() else "NOT_CONFIGURED"}
    def verify_signature(self,body:bytes,signature:str|None)->bool:
        if not settings.alchemy_webhook_signing_key or not signature: return False
        received=signature.removeprefix("sha256=").strip()
        expected=hmac.new(settings.alchemy_webhook_signing_key.encode(),body,hashlib.sha256).hexdigest()
        return hmac.compare_digest(expected,received)

class AlchemyWebhookNormalizer:
    provider="Alchemy Address Activity Webhook"
    def normalize(self,payload:dict,received_at:datetime|None=None)->list[RealtimeEvent]:
        received_at=received_at or datetime.now(timezone.utc)
        event=payload.get("event") if isinstance(payload,dict) else None
        if not isinstance(event,dict): raise ValueError("Alchemy webhook event object is required")
        activities=event.get("activity")
        if not isinstance(activities,list): raise ValueError("Alchemy webhook activity list is required")
        result=[]; network=str(event.get("network") or "").lower()
        if network and "eth" not in network: raise ValueError("Only Ethereum Alchemy activity is configured")
        for index,item in enumerate(activities):
            if not isinstance(item,dict): raise ValueError("Malformed Alchemy activity item")
            source=item.get("fromAddress") or item.get("from") or ""; target=item.get("toAddress") or item.get("to") or ""; tx=item.get("hash") or item.get("transactionHash") or ""
            if not ADDRESS_RE.fullmatch(source) or not ADDRESS_RE.fullmatch(target): raise ValueError("Malformed address in Alchemy activity")
            if not isinstance(tx,str) or not re.fullmatch(r"0x[0-9a-fA-F]{64}",tx): raise ValueError("Malformed transaction hash in Alchemy activity")
            raw_contract=item.get("rawContract") or {}; contract=raw_contract.get("address"); asset=str(item.get("asset") or "ETH"); transfer_index=item.get("logIndex") if item.get("logIndex") is not None else index
            if isinstance(transfer_index, str):
                transfer_index = int(transfer_index, 0)
            provider_id=str(payload.get("id") or payload.get("webhookId") or "")+":"+str(transfer_index)+":"+tx
            identity=event_identity(Chain.ETHEREUM,tx,transfer_index,"REORG" if item.get("removed") else "ADDRESS_ACTIVITY",source,target,asset)
            result.append(RealtimeEvent(event_id=identity,provider=self.provider,provider_event_id=provider_id or None,chain=Chain.ETHEREUM,event_type=RealtimeEventType.REORG if item.get("removed") else RealtimeEventType.ADDRESS_ACTIVITY,received_at=received_at,block_number=int(item["blockNum"],16) if isinstance(item.get("blockNum"),str) else item.get("blockNum"),transaction_hash=tx,transfer_index=int(transfer_index) if transfer_index is not None else None,from_address=source.lower(),to_address=target.lower(),asset=asset,amount=str(item.get("value") or "0"),contract_address=contract,token_id=str(item.get("tokenId")) if item.get("tokenId") is not None else None,raw_provider_reference={"payload":payload,"activity_index":index},removed=bool(item.get("removed")),processing_status=RealtimeProcessingStatus.NORMALIZED,confirmation_state=ConfirmationState.REORGED if item.get("removed") else ConfirmationState.OBSERVED))
        return result

def event_identity(chain:Chain,tx_hash:str,transfer_index:int|None,event_type:str,source:str,target:str,asset:str)->str:
    raw="|".join([str(chain),tx_hash.lower(),str(transfer_index if transfer_index is not None else ""),event_type,source.lower(),target.lower(),asset.lower()])
    return sha256(raw.encode()).hexdigest()

class IncrementalGraphUpdater:
    def validate(self,event:RealtimeEvent):
        if not ADDRESS_RE.fullmatch(event.from_address) or not ADDRESS_RE.fullmatch(event.to_address): raise ValueError("Realtime event contains malformed address")
        if event.from_address=="" or event.to_address=="": raise ValueError("Realtime event addresses are required")
        return event
    def transfer(self,event:RealtimeEvent)->Transfer:
        return Transfer(tx_hash=event.transaction_hash,chain=event.chain,block_number=event.block_number,timestamp=event.observed_at,source=event.from_address,destination=event.to_address,asset=event.asset,amount=event.amount,provider=event.provider,transfer_type="token" if event.contract_address else "native",contract_address=event.contract_address,token_id=event.token_id,raw_reference=event.raw_provider_reference)
